### ISSUE TITLE
Error of hdf5.vstr while execute oq engine

### ISSUE THREAD

**Issue by vup1120** [gem/oq-engine#2138]
Hi, 
I have tried to run oq engine 2.0 on my machine.  I updated my repository of oq-engine, but keep having this error message as shown below. 
Anirudh said the issue should be fixed yesterday, but even after updating my repository, I still have this error.  

Shin-2:GEM yenshin$ oq engine --help
Traceback (most recent call last):
  File "/Users/yenshin/Library/GEM/oq-engine/bin/oq", line 44, in <module>
    oq()
  File "/Users/yenshin/Library/GEM/oq-engine/bin/oq", line 39, in oq
    parsers = [importlib.import_module(modname).parser for modname in modnames]
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/yenshin/Library/GEM/oq-engine/openquake/commands/engine.py", line 26, in <module>
    from openquake.engine import engine as eng, config, logs
  File "/Users/yenshin/Library/GEM/oq-engine/openquake/engine/engine.py", line 29, in <module>
    from openquake.commonlib import parallel, readinput
  File "/Users/yenshin/Library/GEM/oq-engine/openquake/commonlib/readinput.py", line 43, in <module>
    from openquake.commonlib import source, sourceconverter
  File "/Users/yenshin/Library/GEM/oq-engine/openquake/commonlib/source.py", line 512, in <module>
    ('name', hdf5.vstr),
AttributeError: 'module' object has no attribute 'vstr'

**Comment by micheles** [comment]
Yen-Shin, you must update hazardlib, you have an old version of it.

**Comment by vup1120** [comment]
Thank you Michele!
