### ISSUE TITLE
error when deleting calculation `oq engine --dc CALCULATION_ID` 

### ISSUE THREAD

**Issue by CatalinaYepes** [gem/oq-engine#2155]
when trying to delete a calculation I get:

```
oq engine --dc CALCULATION_ID
Traceback (most recent call last):
  File "/usr/local/openquake/oq-engine/bin/oq", line 44, in <module>
    oq()
  File "/usr/local/openquake/oq-engine/bin/oq", line 41, in oq
    parser.callfunc()
  File "/usr/local/openquake/oq-engine/openquake/commonlib/sap.py", line 177, in callfunc
    return self.func(**vars(namespace))
  File "/usr/local/openquake/oq-engine/openquake/commonlib/sap.py", line 232, in main
    return func(**kw)
  File "/usr/local/openquake/oq-engine/openquake/commands/engine.py", line 189, in engine
    delete_calculation(delete_calculation, yes)
TypeError: 'str' object is not callable
```

Another error also occurs when trying to delete the "uncompleted calculations"

```
oq engine --duc
Traceback (most recent call last):
  File "/usr/local/openquake/oq-engine/bin/oq", line 44, in <module>
    oq()
  File "/usr/local/openquake/oq-engine/bin/oq", line 41, in oq
    parser.callfunc()
  File "/usr/local/openquake/oq-engine/openquake/commonlib/sap.py", line 177, in callfunc
    return self.func(**vars(namespace))
  File "/usr/local/openquake/oq-engine/openquake/commonlib/sap.py", line 232, in main
    return func(**kw)
  File "/usr/local/openquake/oq-engine/openquake/commands/engine.py", line 236, in engine
    logs.dbcmd('delete_uncompleted_calculations', getpass.getuser())
  File "/usr/local/openquake/oq-engine/openquake/engine/logs.py", line 61, in dbcmd
    raise etype(res)
RuntimeError:
  File "/usr/local/openquake/oq-engine/openquake/commonlib/parallel.py", line 107, in safely_call
    got = func(*args)
  File "/usr/local/openquake/oq-engine/openquake/server/db/actions.py", line 102, in delete_uncompleted_calculations
    oqjob__status="complete"):
  File "/usr/local/openquake/oq-engine/openquake/server/db/actions.py", line 288, in del_calc
    raise RuntimeError(
RuntimeError: Unable to delete hazard calculation: The following risk calculations are referencing this hazard calculation: 9920
```

**Comment by micheles** [comment]
The error happens on Wilson with `$ oq engine --dc 10492`

**Comment by micheles** [comment]
Notice that the problem with --duc has been already solved in https://github.com/gem/oq-engine/pull/2152
