### ISSUE TITLE
Casting error on a 32bit environment

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#2306]
During the risk workshop some attendees got this error in the event based, in the function `filter_sites_by_distance_to_source`:

https://api.asm.skype.com/v1/objects/0-weu-d3-13beed00012bf6f83468d38ee3236981/views/imgpsh_fullsize

**Comment by daniviga** [comment]
Skype link can't be shared. Can you attach the real picture? (You need just to drag and drop it on the editor)

**Comment by raoanirudh** [comment]
<img width="962" alt="casting-error" src="https://cloud.githubusercontent.com/assets/1707414/19476696/e4d51a46-953a-11e6-8186-5cb20082fadd.png">

**Comment by daniviga** [comment]
Thanks @raoanirudh! This happened on all the machines or on some of them? Is it always reproducible? Is it possible to have the input files?

**Comment by CatalinaYepes** [comment]
Three different participants have the same error while running different models. Find here an example.

[EventBasedRisk (1).zip](https://github.com/gem/oq-engine/files/536137/EventBasedRisk.1.zip)

**Comment by daniviga** [comment]
Thanks @CatalinaYepes, I'll try it on my Win machine and on WINE.

**Comment by daniviga** [comment]
I suspect that this is broken on Linux 32bit too.

**Comment by daniviga** [comment]
@CatalinaYepes are you sure it's the right calculation? It almost ran out of memory on my 12GB laptop using the native linux environment. It big for an average Windows laptop with 8 gigs.

**Comment by daniviga** [comment]
I can confirm that the issue is unrelated to Windows, but it affects all the 32bit installations, including Linux.

Ccurrently we are providing a 32bit only installer for WIndows; a 64bit installer is scheduled for 2.2.0. Linux supports 32bit only on Ubuntu (no RHEL, no OPT).

This is the result on our 32bit VM running Ubuntu Trusty
```python
TypeError: 
  File "/usr/lib/python2.7/dist-packages/openquake/commonlib/parallel.py", line 113, in safely_call
    got = func(*args)
  File "/usr/lib/python2.7/dist-packages/openquake/calculators/event_based.py", line 244, in compute_ruptures
    s_sites = src.filter_sites_by_distance_to_source(max_dist, sitecol)
  File "/usr/lib/python2.7/dist-packages/openquake/hazardlib/source/base.py", line 153, in filter_sites_by_distance_to_source
    return sites.filter(rup_enc_poly.intersects(sites.mesh))
  File "/usr/lib/python2.7/dist-packages/openquake/hazardlib/site.py", line 368, in mesh
    return Mesh(self.lons, self.lats, depths=None)
  File "/usr/lib/python2.7/dist-packages/openquake/hazardlib/site.py", line 484, in <lambda>
    lambda fsc, name=name: _extract_site_param(fsc, name),
  File "/usr/lib/python2.7/dist-packages/openquake/hazardlib/site.py", line 478, in _extract_site_param
    return getattr(fsc.complete, name).take(fsc.indices)
TypeError: Cannot cast array data from dtype('int64') to dtype('int32') according to the rule 'safe'
```

**Comment by raoanirudh** [comment]
Log from the Nepal event based risk demo on a Windows laptop:

```sh
2016-10-18T13:18:13.88,INFO,MainProcess/2592,Using engine version 2.1.0

2016-10-18T13:18:13.98,INFO,MainProcess/2592,Using hazardlib version 0.21.0

2016-10-18T13:18:14.15,INFO,MainProcess/2592,Reading the exposure

2016-10-18T13:18:17.85,INFO,MainProcess/2592,Read 9144 assets within the region_constraint and discarded 0 assets outside the region

2016-10-18T13:18:20.31,INFO,MainProcess/2592,Instantiating the source-sites filter

2016-10-18T13:18:21.02,INFO,MainProcess/2592,Instantiated 398 sources from C:\Program Files (x86)\OpenQuake Engine\demos\risk\EventBasedRisk\source_model.xml

2016-10-18T13:18:51.67,INFO,MainProcess/2592,Processed source model 1/1 with 1 gsim path(s)

2016-10-18T13:18:51.80,INFO,MainProcess/2592,Filtering composite source model

2016-10-18T13:18:52.27,INFO,MainProcess/2592,Using a maxweight of 200

2016-10-18T13:18:52.38,INFO,MainProcess/2592,Sending source group #1 of 1 (Active Shallow Crust, 31 sources)

2016-10-18T13:18:52.49,INFO,MainProcess/2592,Submitting  "compute_ruptures" tasks

2016-10-18T13:18:54.01,INFO,MainProcess/2592,Splitting AreaSource "230" in 348 sources

2016-10-18T13:18:56.01,INFO,MainProcess/2592,Splitting AreaSource "235" in 514 sources

2016-10-18T13:18:58.17,INFO,MainProcess/2592,Splitting AreaSource "236" in 303 sources

2016-10-18T13:18:59.81,INFO,MainProcess/2592,Splitting AreaSource "244" in 276 sources

2016-10-18T13:19:00.09,INFO,MainProcess/2592,Sent 15 light and 6 heavy tasks

2016-10-18T13:19:00.29,INFO,MainProcess/2592,Sent 1.53 MB of data in 21 task(s)

2016-10-18T13:19:00.62,INFO,MainProcess/2592,compute_ruptures   4%

2016-10-18T13:19:01.01,INFO,MainProcess/2592,compute_ruptures   9%

2016-10-18T13:19:01.27,INFO,MainProcess/2592,compute_ruptures  14%

2016-10-18T13:19:01.54,INFO,MainProcess/2592,compute_ruptures  19%

2016-10-18T13:19:01.97,INFO,MainProcess/2592,compute_ruptures  23%

2016-10-18T13:19:02.15,INFO,MainProcess/2592,compute_ruptures  28%

2016-10-18T13:19:02.29,INFO,MainProcess/2592,compute_ruptures  33%

2016-10-18T13:19:02.44,INFO,MainProcess/2592,compute_ruptures  38%

2016-10-18T13:19:03.16,INFO,MainProcess/2592,compute_ruptures  42%

2016-10-18T13:19:03.65,INFO,MainProcess/2592,compute_ruptures  47%

2016-10-18T13:19:03.89,INFO,MainProcess/2592,compute_ruptures  52%

2016-10-18T13:19:04.05,INFO,MainProcess/2592,compute_ruptures  57%

2016-10-18T13:19:04.31,CRITICAL,MainProcess/2592,

2016-10-18T13:19:04.46,CRITICAL,MainProcess/2592,

2016-10-18T13:19:04.60,CRITICAL,MainProcess/2592,

2016-10-18T13:19:04.75,CRITICAL,MainProcess/2592,Traceback (most recent call last):
  File "C:\Program Files (x86)\OpenQuake Engine\lib\openquake\engine\engine.py", line 179, in run_calc
    _do_run_calc(calc, exports, hazard_calculation_id)
  File "C:\Program Files (x86)\OpenQuake Engine\lib\openquake\engine\engine.py", line 212, in _do_run_calc
    close=False)  # don't close the datastore too soon
  File "C:\Program Files (x86)\OpenQuake Engine\lib\openquake\calculators\base.py", line 191, in run
    self.pre_execute()
  File "C:\Program Files (x86)\OpenQuake Engine\lib\openquake\calculators\event_based_risk.py", line 224, in pre_execute
    super(EventBasedRiskCalculator, self).pre_execute()
  File "C:\Program Files (x86)\OpenQuake Engine\lib\openquake\calculators\base.py", line 419, in pre_execute
    self.precalc = (self.compute_previous() if precalc_id is None
  File "C:\Program Files (x86)\OpenQuake Engine\lib\openquake\calculators\base.py", line 362, in compute_previous
    precalc.run(close=False)
  File "C:\Program Files (x86)\OpenQuake Engine\lib\openquake\calculators\base.py", line 191, in run
    self.pre_execute()
  File "C:\Program Files (x86)\OpenQuake Engine\lib\openquake\calculators\base.py", line 419, in pre_execute
    self.precalc = (self.compute_previous() if precalc_id is None
  File "C:\Program Files (x86)\OpenQuake Engine\lib\openquake\calculators\base.py", line 362, in compute_previous
    precalc.run(close=False)
  File "C:\Program Files (x86)\OpenQuake Engine\lib\openquake\calculators\base.py", line 192, in run
    self.result = self.execute()
  File "C:\Program Files (x86)\OpenQuake Engine\lib\openquake\calculators\classical.py", line 323, in execute
    acc = reduce(self.agg_dicts, res, self.zerodict())
  File "C:\Program Files (x86)\OpenQuake Engine\lib\openquake\commonlib\parallel.py", line 262, in __iter__
    raise etype(val)
TypeError: 
  File "C:\Program Files (x86)\OpenQuake Engine\lib\openquake\commonlib\parallel.py", line 113, in safely_call
    got = func(*args)
  File "C:\Program Files (x86)\OpenQuake Engine\lib\openquake\calculators\event_based.py", line 244, in compute_ruptures
    s_sites = src.filter_sites_by_distance_to_source(max_dist, sitecol)
  File "C:\Program Files (x86)\OpenQuake Engine\lib\openquake\hazardlib\source\point.py", line 147, in filter_sites_by_distance_to_source
    return sites.filter(self.location.closer_than(sites.mesh, radius))
  File "C:\Program Files (x86)\OpenQuake Engine\lib\openquake\hazardlib\site.py", line 368, in mesh
    return Mesh(self.lons, self.lats, depths=None)
  File "C:\Program Files (x86)\OpenQuake Engine\lib\openquake\hazardlib\site.py", line 484, in <lambda>
    lambda fsc, name=name: _extract_site_param(fsc, name),
  File "C:\Program Files (x86)\OpenQuake Engine\lib\openquake\hazardlib\site.py", line 478, in _extract_site_param
    return getattr(fsc.complete, name).take(fsc.indices)
TypeError: Cannot cast array data from dtype('int64') to dtype('int32') according to the rule 'safe'
```

**Comment by daniviga** [comment]
I can confirm that `Stochastic Event-Based Risk Demo (Nepal)` does not work in the 32bit Linux VM (same error). I'm pretty sure that it was working in the past. I will check the old VMs.

**Comment by daniviga** [comment]
The Nepal EB Risk Demo was working with OQ 2.0, so we have a regression:

```bash
2016-10-18T14:40:43.20,INFO,MainProcess/1680,Using engine version 2.0.0
2016-10-18T14:40:43.26,INFO,MainProcess/1680,Reading the exposure
2016-10-18T14:40:46.31,INFO,MainProcess/1680,Read 9144 assets within the region_constraint and discarded 0 assets outside the region
2016-10-18T14:40:48.77,INFO,MainProcess/1680,Parsed 398 sources from /tmp/tmpi71HIM/EventBasedRisk/source_model.xml
2016-10-18T14:41:17.90,INFO,MainProcess/1680,Processed source model 1/1 with 1 gsim path(s)
2016-10-18T14:41:18.05,INFO,MainProcess/1680,Instantiated SourceManager with maxweight=272.0
2016-10-18T14:41:18.10,INFO,MainProcess/1680,Filtering light sources
2016-10-18T14:41:20.88,INFO,MainProcess/1680,Submitting task compute_ruptures #1
2016-10-18T14:41:20.94,INFO,MainProcess/1680,Submitting task compute_ruptures #2
2016-10-18T14:41:20.99,INFO,MainProcess/1680,Submitting task compute_ruptures #3
2016-10-18T14:41:21.03,INFO,MainProcess/1680,Sent 27 sources in 3 block(s)
2016-10-18T14:41:21.10,INFO,MainProcess/1680,Filtering heavy sources
2016-10-18T14:41:21.17,INFO,MainProcess/1680,Sent 283.2 KB of data in 3 task(s)
2016-10-18T14:41:27.68,INFO,MainProcess/1680,compute_ruptures  33%
2016-10-18T14:41:30.58,INFO,MainProcess/1680,compute_ruptures  66%
2016-10-18T14:41:33.38,INFO,MainProcess/1680,compute_ruptures 100%
2016-10-18T14:41:33.43,INFO,MainProcess/1680,Received 4.39 MB of data, maximum per task 2.58 MB
2016-10-18T14:41:33.60,INFO,MainProcess/1680,Saving SES collection with 1647 ruptures, 2167 events
2016-10-18T14:41:36.81,INFO,MainProcess/1680,Populating the risk inputs
2016-10-18T14:41:40.16,INFO,MainProcess/1680,Building (2273, 2167) epsilons for taxonomy Adobe
2016-10-18T14:41:40.73,INFO,MainProcess/1680,Building (52, 2167) epsilons for taxonomy Concrete
2016-10-18T14:41:40.79,INFO,MainProcess/1680,Building (2273, 2167) epsilons for taxonomy Stone-Masonry
2016-10-18T14:41:41.29,INFO,MainProcess/1680,Building (2273, 2167) epsilons for taxonomy Unreinforced-Brick-Masonry
2016-10-18T14:41:41.80,INFO,MainProcess/1680,Building (2273, 2167) epsilons for taxonomy Wood
2016-10-18T14:41:42.30,INFO,MainProcess/1680,Generated (9144, 2167) epsilons
2016-10-18T14:41:42.35,INFO,MainProcess/1680,minimum_intensity={'PGA': 0.05}
2016-10-18T14:41:42.47,INFO,MainProcess/1680,Submitting task event_based_risk #1
2016-10-18T14:41:42.62,INFO,MainProcess/1680,Submitting task event_based_risk #2
2016-10-18T14:41:42.78,INFO,MainProcess/1680,Submitting task event_based_risk #3
2016-10-18T14:41:42.97,INFO,MainProcess/1680,Submitting task event_based_risk #4
2016-10-18T14:41:43.12,INFO,MainProcess/1680,Submitting task event_based_risk #5
2016-10-18T14:41:43.32,INFO,MainProcess/1680,Submitting task event_based_risk #6
2016-10-18T14:41:43.52,INFO,MainProcess/1680,Submitting task event_based_risk #7
2016-10-18T14:41:43.71,INFO,MainProcess/1680,Submitting task event_based_risk #8
2016-10-18T14:41:43.92,INFO,MainProcess/1680,Submitting task event_based_risk #9
2016-10-18T14:41:44.20,INFO,MainProcess/1680,Submitting task event_based_risk #10
2016-10-18T14:41:44.46,INFO,MainProcess/1680,Submitting task event_based_risk #11
2016-10-18T14:41:44.70,INFO,MainProcess/1680,Submitting task event_based_risk #12
2016-10-18T14:41:45.27,INFO,MainProcess/1680,Submitting task event_based_risk #13
2016-10-18T14:41:45.82,INFO,MainProcess/1680,Submitting task event_based_risk #14
2016-10-18T14:41:46.28,INFO,MainProcess/1680,Submitting task event_based_risk #15
2016-10-18T14:41:47.12,INFO,MainProcess/1680,Submitting task event_based_risk #16
2016-10-18T14:41:47.42,INFO,MainProcess/1680,Submitting task event_based_risk #17
2016-10-18T14:41:47.50,INFO,MainProcess/1680,Sent 94.92 MB of data in 17 task(s)
2016-10-18T14:41:48.41,INFO,MainProcess/1680,event_based_risk   5%
2016-10-18T14:41:48.95,INFO,MainProcess/1680,event_based_risk  11%
2016-10-18T14:41:55.12,INFO,MainProcess/1680,event_based_risk  17%
2016-10-18T14:41:56.61,INFO,MainProcess/1680,event_based_risk  23%
2016-10-18T14:42:03.14,INFO,MainProcess/1680,event_based_risk  29%
2016-10-18T14:42:04.01,INFO,MainProcess/1680,event_based_risk  35%
2016-10-18T14:42:08.91,INFO,MainProcess/1680,event_based_risk  41%
2016-10-18T14:42:09.11,INFO,MainProcess/1680,event_based_risk  47%
2016-10-18T14:42:13.03,INFO,MainProcess/1680,event_based_risk  52%
2016-10-18T14:42:14.48,INFO,MainProcess/1680,event_based_risk  58%
2016-10-18T14:42:18.04,INFO,MainProcess/1680,event_based_risk  64%
2016-10-18T14:42:21.22,INFO,MainProcess/1680,event_based_risk  70%
2016-10-18T14:42:22.11,INFO,MainProcess/1680,event_based_risk  76%
2016-10-18T14:42:22.46,INFO,MainProcess/1680,event_based_risk  82%
2016-10-18T14:42:24.46,INFO,MainProcess/1680,event_based_risk  88%
2016-10-18T14:42:25.03,INFO,MainProcess/1680,event_based_risk  94%
2016-10-18T14:42:25.35,INFO,MainProcess/1680,event_based_risk 100%
2016-10-18T14:42:25.41,INFO,MainProcess/1680,Received 12.6 MB of data, maximum per task 1.54 MB
2016-10-18T14:42:25.47,INFO,MainProcess/1680,Generated 413.05 KB of GMFs
2016-10-18T14:42:25.85,INFO,MainProcess/1680,Starting 2 tasks
2016-10-18T14:42:25.90,INFO,MainProcess/1680,Submitting task build_agg_curve #1
2016-10-18T14:42:25.95,INFO,MainProcess/1680,Submitting task build_agg_curve #2
2016-10-18T14:42:26.01,INFO,MainProcess/1680,Sent 23.23 KB of data in 2 task(s)
2016-10-18T14:42:26.09,INFO,MainProcess/1680,build_agg_curve  50%
2016-10-18T14:42:26.14,INFO,MainProcess/1680,build_agg_curve 100%
2016-10-18T14:42:26.18,INFO,MainProcess/1680,Received 3.69 KB of data, maximum per task 1.84 KB
2016-10-18T14:42:26.24,INFO,MainProcess/1680,Saved 656 B in agg_curve-rlzs
2016-10-18T14:42:26.29,INFO,MainProcess/1680,Saved 1.67 MB in rcurves-rlzs
2016-10-18T14:42:26.36,WARNING,MainProcess/1680,/usr/lib/python2.7/dist-packages/openquake/risklib/scientific.py:1039: DeprecationWarning: using a boolean instead of an integer will result in an error in the future
  asset_values, poe, curves_lt[:, rlzi, ins])
2016-10-18T14:42:28.96,INFO,MainProcess/1680,Calculation 1 finished correctly in 105 seconds
```

**Comment by daniviga** [comment]
It seems to me that we have an int on the engine side that is forcefully set to int64 instead on the hazarlib side the size of the integers is depending on the underlying architecture
