### ISSUE TITLE
Caracas event-based risk calculation issue

### ISSUE THREAD

**Issue by mabevillar** [gem/oq-engine#2616]
Couldn't run and event-based risk calculation for Caracas

Files regarding this issue can be found at my GEMMICRO02 folder: /home/mvillar/Scenarios2/05_Caracas/02_Inputs

```
mvillar@gemmicro02:~/Scenarios2/05_Caracas/02_Inputs$ oq engine --run job_caracas.ini
[2017-03-03 18:16:21,840 #385 INFO] Using engine version 2.4.0-git6ec276b
[2017-03-03 18:16:21,966 #385 INFO] Using hazardlib version 0.24.0-git3e39f4b
[2017-03-03 18:16:22,160 #385 INFO] Reading the exposure
[2017-03-03 18:19:56,479 #385 INFO] Building the site collection
[2017-03-03 21:10:36,006 #385 INFO] Read 120883 assets on 12680 sites
[2017-03-03 21:10:45,246 #385 INFO] Instantiating the source-sites filter
[2017-03-03 21:12:00,619 #385 INFO] Instantiated 10000 sources from /home/mvillar/Scenarios2/05_Caracas/02_Inputs/sara_source_model_1_ven.xml
[2017-03-03 21:12:02,703 #385 INFO] Instantiated 20000 sources from /home/mvillar/Scenarios2/05_Caracas/02_Inputs/sara_source_model_1_ven.xml
[2017-03-03 21:12:05,978 #385 INFO] Instantiated 30000 sources from /home/mvillar/Scenarios2/05_Caracas/02_Inputs/sara_source_model_1_ven.xml
[2017-03-03 21:12:11,953 #385 INFO] Instantiated 40000 sources from /home/mvillar/Scenarios2/05_Caracas/02_Inputs/sara_source_model_1_ven.xml
[2017-03-03 21:12:13,562 #385 INFO] Instantiated 44479 sources from /home/mvillar/Scenarios2/05_Caracas/02_Inputs/sara_source_model_1_ven.xml
[2017-03-03 21:13:09,325 #385 INFO] Processed source model 1 with 54 gsim path(s)
[2017-03-03 21:13:10,266 #385 INFO] Filtering composite source model
[2017-03-03 21:15:25,463 #385 INFO] Using a maxweight of 517
[2017-03-03 21:15:25,598 #385 INFO] Sending source group #1 of 4 (Subduction Interface, 1 sources)
[2017-03-03 21:15:48,171 #385 INFO] Splitting ComplexFaultSource "i01" in 10 sources
[2017-03-03 21:15:48,318 #385 INFO] Submitting  "compute_ruptures" tasks
[2017-03-03 21:15:48,527 #385 INFO] Sending source group #2 of 4 (Subduction IntraSlab, 722 sources)
[2017-03-03 21:15:48,832 #385 INFO] Sending source group #3 of 4 (Active Shallow Crust, 3473 sources)
[2017-03-03 21:15:54,869 #385 INFO] Splitting SimpleFaultSource "VE01-01a" in 18 sources
[2017-03-03 21:15:55,571 #385 INFO] Splitting SimpleFaultSource "VE01-05" in 10 sources
[2017-03-03 21:15:56,265 #385 INFO] Splitting SimpleFaultSource "VE01-08" in 11 sources
[2017-03-03 21:15:57,515 #385 INFO] Splitting SimpleFaultSource "VE01-10a" in 14 sources
[2017-03-03 21:15:59,040 #385 INFO] Splitting SimpleFaultSource "VE01-10b" in 13 sources
[2017-03-03 21:16:00,116 #385 INFO] Splitting SimpleFaultSource "VE01-10c" in 13 sources
[2017-03-03 21:16:02,015 #385 INFO] Splitting SimpleFaultSource "VE01-10d" in 13 sources
[2017-03-03 21:16:02,670 #385 INFO] Splitting SimpleFaultSource "VE01-12e" in 11 sources
[2017-03-03 21:16:03,935 #385 INFO] Splitting SimpleFaultSource "VE01-12f" in 13 sources
[2017-03-03 21:16:05,328 #385 INFO] Splitting SimpleFaultSource "VE01-12g" in 12 sources
[2017-03-03 21:16:06,292 #385 INFO] Splitting SimpleFaultSource "VE01-12h" in 11 sources
[2017-03-03 21:16:07,275 #385 INFO] Splitting SimpleFaultSource "VE02-01d" in 13 sources
[2017-03-03 21:16:08,344 #385 INFO] Splitting SimpleFaultSource "VE02-01e" in 16 sources
[2017-03-03 21:16:09,689 #385 INFO] Splitting SimpleFaultSource "VE02-01f" in 16 sources
[2017-03-03 21:16:12,239 #385 INFO] Splitting SimpleFaultSource "VE02-06d" in 18 sources
[2017-03-03 21:16:13,381 #385 INFO] Splitting SimpleFaultSource "VE02-08b" in 10 sources
[2017-03-03 21:16:13,912 #385 INFO] Splitting SimpleFaultSource "VE02-15" in 14 sources
[2017-03-03 21:16:15,441 #385 INFO] Splitting SimpleFaultSource "VE02-27" in 12 sources
[2017-03-03 21:16:16,029 #385 INFO] Splitting SimpleFaultSource "VE02-28" in 11 sources
[2017-03-03 21:16:22,886 #385 INFO] Splitting SimpleFaultSource "VE02-47a" in 21 sources
[2017-03-03 21:16:25,831 #385 INFO] Splitting SimpleFaultSource "VE02-47e" in 20 sources
[2017-03-03 21:16:28,115 #385 INFO] Splitting SimpleFaultSource "VE03-01" in 16 sources
[2017-03-03 21:16:29,615 #385 INFO] Splitting SimpleFaultSource "VE03-03b" in 17 sources
[2017-03-03 21:16:31,303 #385 INFO] Splitting SimpleFaultSource "VE03-03d" in 16 sources
[2017-03-03 21:16:32,112 #385 INFO] Splitting SimpleFaultSource "VE03-07b" in 11 sources
[2017-03-03 21:16:33,309 #385 INFO] Splitting SimpleFaultSource "VE03-09a" in 14 sources
[2017-03-03 21:16:34,198 #385 INFO] Splitting SimpleFaultSource "VE03-09b" in 14 sources
[2017-03-03 21:16:34,825 #385 INFO] Splitting SimpleFaultSource "VE03-09e" in 11 sources
[2017-03-03 21:16:35,728 #385 INFO] Splitting SimpleFaultSource "VE03-09f" in 12 sources
[2017-03-03 21:16:36,712 #385 INFO] Splitting SimpleFaultSource "VE03-10" in 13 sources
[2017-03-03 21:16:37,763 #385 INFO] Splitting SimpleFaultSource "VE03-11" in 14 sources
[2017-03-03 21:16:39,131 #385 INFO] Splitting SimpleFaultSource "VE03-12a" in 16 sources
[2017-03-03 21:16:40,657 #385 INFO] Splitting SimpleFaultSource "VE04-01a" in 16 sources
[2017-03-03 21:16:41,767 #385 INFO] Splitting SimpleFaultSource "VE04-02a" in 15 sources
[2017-03-03 21:16:42,750 #385 INFO] Splitting SimpleFaultSource "VE04-03" in 11 sources
[2017-03-03 21:16:43,971 #385 INFO] Splitting SimpleFaultSource "VE04-04a" in 17 sources
[2017-03-03 21:16:44,450 #385 INFO] Splitting SimpleFaultSource "VE04-05" in 12 sources
[2017-03-03 21:16:45,134 #385 INFO] Splitting SimpleFaultSource "VE04-11a" in 14 sources
[2017-03-03 21:16:46,199 #385 INFO] Splitting SimpleFaultSource "VE04-11b" in 16 sources
[2017-03-03 21:16:48,205 #385 INFO] Splitting SimpleFaultSource "VE04-12a" in 17 sources
[2017-03-03 21:16:49,305 #385 INFO] Splitting SimpleFaultSource "VE04-12c" in 17 sources
[2017-03-03 21:16:51,041 #385 INFO] Splitting SimpleFaultSource "VE04-13a" in 19 sources
[2017-03-03 21:16:51,933 #385 INFO] Splitting SimpleFaultSource "VE04-15a" in 14 sources
[2017-03-03 21:16:52,658 #385 INFO] Splitting SimpleFaultSource "VE04-15b" in 11 sources
[2017-03-03 21:16:53,174 #385 INFO] Splitting SimpleFaultSource "VE04-16a" in 11 sources
[2017-03-03 21:16:53,742 #385 INFO] Splitting SimpleFaultSource "VE04-21" in 12 sources
[2017-03-03 21:16:54,578 #385 INFO] Splitting SimpleFaultSource "VE04-22a" in 14 sources
[2017-03-03 21:16:55,125 #385 INFO] Splitting SimpleFaultSource "VE04-27" in 13 sources
[2017-03-03 21:16:55,321 #385 INFO] Sending source group #4 of 4 (Stable Shallow Crust, 2506 sources)
[2017-03-03 21:16:58,405 #385 INFO] Sent 367.96 MB of data in 506 task(s)
[2017-03-03 21:16:59,817 #385 INFO] compute_ruptures   1%
[2017-03-03 21:17:01,289 #385 INFO] compute_ruptures   2%
[2017-03-03 21:17:04,884 #385 INFO] compute_ruptures   3%
[2017-03-03 21:17:07,609 #385 INFO] compute_ruptures   4%
[2017-03-03 21:17:08,211 #385 INFO] compute_ruptures   5%
[2017-03-03 21:17:09,885 #385 INFO] compute_ruptures   6%
[2017-03-03 21:17:13,292 #385 INFO] compute_ruptures   7%
[2017-03-03 21:17:13,670 #385 INFO] compute_ruptures   8%
[2017-03-03 21:17:15,798 #385 INFO] compute_ruptures   9%
[2017-03-03 21:17:18,087 #385 INFO] compute_ruptures  10%
[2017-03-03 21:17:18,637 #385 INFO] compute_ruptures  11%
[2017-03-03 21:17:19,914 #385 INFO] compute_ruptures  12%
[2017-03-03 21:17:20,427 #385 INFO] compute_ruptures  13%
[2017-03-03 21:17:20,715 #385 INFO] compute_ruptures  14%
[2017-03-03 21:17:21,423 #385 INFO] compute_ruptures  15%
[2017-03-03 21:17:21,939 #385 INFO] compute_ruptures  16%
[2017-03-03 21:17:22,300 #385 INFO] compute_ruptures  17%
[2017-03-03 21:17:23,445 #385 INFO] compute_ruptures  18%
[2017-03-03 21:17:24,312 #385 INFO] compute_ruptures  19%
[2017-03-03 21:17:27,491 #385 INFO] compute_ruptures  20%
[2017-03-03 21:17:28,438 #385 INFO] compute_ruptures  21%
[2017-03-03 21:17:28,999 #385 INFO] compute_ruptures  22%
[2017-03-03 21:17:29,391 #385 INFO] compute_ruptures  23%
[2017-03-03 21:17:29,816 #385 INFO] compute_ruptures  24%
[2017-03-03 21:17:30,220 #385 INFO] compute_ruptures  25%
[2017-03-03 21:17:30,679 #385 INFO] compute_ruptures  26%
[2017-03-03 21:17:30,999 #385 INFO] compute_ruptures  27%
[2017-03-03 21:17:31,453 #385 INFO] compute_ruptures  28%
[2017-03-03 21:17:32,246 #385 INFO] compute_ruptures  29%
[2017-03-03 21:17:35,099 #385 INFO] compute_ruptures  30%
[2017-03-03 21:17:38,085 #385 INFO] compute_ruptures  31%
[2017-03-03 21:17:40,103 #385 INFO] compute_ruptures  32%
[2017-03-03 21:17:47,998 #385 INFO] compute_ruptures  33%
[2017-03-03 21:17:58,947 #385 INFO] compute_ruptures  34%
[2017-03-03 21:18:03,922 #385 INFO] compute_ruptures  35%
[2017-03-03 21:18:13,528 #385 INFO] compute_ruptures  36%
[2017-03-03 21:18:22,032 #385 INFO] compute_ruptures  37%
[2017-03-03 21:18:27,945 #385 INFO] compute_ruptures  38%
[2017-03-03 21:18:37,352 #385 INFO] compute_ruptures  39%
[2017-03-03 21:18:42,629 #385 INFO] compute_ruptures  40%
[2017-03-03 21:18:46,570 #385 INFO] compute_ruptures  41%
[2017-03-03 21:19:02,229 #385 INFO] compute_ruptures  42%
[2017-03-03 21:19:06,488 #385 INFO] compute_ruptures  43%
[2017-03-03 21:19:08,343 #385 INFO] compute_ruptures  44%
[2017-03-03 21:19:10,747 #385 INFO] compute_ruptures  45%
[2017-03-03 21:19:11,947 #385 INFO] compute_ruptures  46%
[2017-03-03 21:19:14,227 #385 INFO] compute_ruptures  47%
[2017-03-03 21:19:16,570 #385 INFO] compute_ruptures  48%
[2017-03-03 21:19:19,896 #385 INFO] compute_ruptures  49%
[2017-03-03 21:19:29,021 #385 INFO] compute_ruptures  50%
[2017-03-03 21:19:31,797 #385 INFO] compute_ruptures  51%
[2017-03-03 21:19:33,048 #385 INFO] compute_ruptures  52%
[2017-03-03 21:19:33,781 #385 INFO] compute_ruptures  53%
[2017-03-03 21:19:35,924 #385 INFO] compute_ruptures  54%
[2017-03-03 21:19:39,949 #385 INFO] compute_ruptures  55%
[2017-03-03 21:19:42,017 #385 INFO] compute_ruptures  56%
[2017-03-03 21:19:43,441 #385 INFO] compute_ruptures  57%
[2017-03-03 21:19:45,269 #385 INFO] compute_ruptures  58%
[2017-03-03 21:19:46,624 #385 INFO] compute_ruptures  59%
[2017-03-03 21:19:48,890 #385 INFO] compute_ruptures  60%
[2017-03-03 21:19:50,662 #385 INFO] compute_ruptures  61%
[2017-03-03 21:19:51,546 #385 INFO] compute_ruptures  62%
[2017-03-03 21:19:53,260 #385 INFO] compute_ruptures  63%
[2017-03-03 21:19:53,984 #385 INFO] compute_ruptures  64%
[2017-03-03 21:19:55,133 #385 INFO] compute_ruptures  65%
[2017-03-03 21:19:56,099 #385 INFO] compute_ruptures  66%
[2017-03-03 21:19:57,217 #385 INFO] compute_ruptures  67%
[2017-03-03 21:19:58,339 #385 INFO] compute_ruptures  68%
[2017-03-03 21:19:59,118 #385 INFO] compute_ruptures  69%
[2017-03-03 21:19:59,810 #385 INFO] compute_ruptures  70%
[2017-03-03 21:20:01,023 #385 INFO] compute_ruptures  71%
[2017-03-03 21:20:01,375 #385 INFO] compute_ruptures  72%
[2017-03-03 21:20:02,392 #385 INFO] compute_ruptures  73%
[2017-03-03 21:20:02,884 #385 INFO] compute_ruptures  74%
[2017-03-03 21:20:03,606 #385 INFO] compute_ruptures  75%
[2017-03-03 21:20:04,041 #385 INFO] compute_ruptures  76%
[2017-03-03 21:20:04,469 #385 INFO] compute_ruptures  77%
[2017-03-03 21:20:05,012 #385 INFO] compute_ruptures  78%
[2017-03-03 21:20:05,816 #385 INFO] compute_ruptures  79%
[2017-03-03 21:20:06,661 #385 INFO] compute_ruptures  80%
[2017-03-03 21:20:07,104 #385 INFO] compute_ruptures  81%
[2017-03-03 21:20:07,689 #385 INFO] compute_ruptures  82%
[2017-03-03 21:20:08,241 #385 INFO] compute_ruptures  83%
[2017-03-03 21:20:08,747 #385 INFO] compute_ruptures  84%
[2017-03-03 21:20:09,005 #385 INFO] compute_ruptures  85%
[2017-03-03 21:20:09,344 #385 INFO] compute_ruptures  86%
[2017-03-03 21:20:10,185 #385 INFO] compute_ruptures  87%
[2017-03-03 21:20:10,492 #385 INFO] compute_ruptures  88%
[2017-03-03 21:20:11,772 #385 INFO] compute_ruptures  89%
[2017-03-03 21:20:12,261 #385 INFO] compute_ruptures  90%
[2017-03-03 21:20:12,983 #385 INFO] compute_ruptures  91%
[2017-03-03 21:20:13,422 #385 INFO] compute_ruptures  92%
[2017-03-03 21:20:14,527 #385 INFO] compute_ruptures  93%
[2017-03-03 21:20:14,944 #385 INFO] compute_ruptures  94%
[2017-03-03 21:20:28,959 #385 INFO] compute_ruptures  95%
[2017-03-03 21:21:11,380 #385 INFO] compute_ruptures  96%
[2017-03-03 21:21:21,928 #385 INFO] compute_ruptures  97%
[2017-03-03 21:22:14,962 #385 INFO] compute_ruptures  98%
[2017-03-03 21:24:15,870 #385 INFO] compute_ruptures  99%
[2017-03-03 21:29:31,083 #385 INFO] compute_ruptures 100%
[2017-03-03 21:29:31,268 #385 INFO] Received 4.63 GB of data, maximum per task 244.19 MB
[2017-03-03 21:29:31,647 #385 INFO] Setting 239167 event years
[2017-03-03 21:29:41,355 #385 INFO] minimum_intensity={'SA(1.0)': 0.050000000000000003, 'SA(0.3)': 0.050000000000000003, 'PGA': 0.050000000000000003}
[2017-03-03 21:29:50,584 #385 INFO] Submitting 79 "event_based_risk#1" tasks
[2017-03-03 21:30:42,971 #385 INFO] Sent 5.07 GB of data in 79 task(s)
[2017-03-03 21:30:49,449 #385 CRITICAL]
Traceback (most recent call last):
  File "/usr/local/openquake/oq-engine/openquake/calculators/base.py", line 197, in run
    self.result = self.execute()
  File "/usr/local/openquake/oq-engine/openquake/calculators/event_based_risk.py", line 476, in execute
    num_events = self.save_results(allres, num_rlzs)
  File "/usr/local/openquake/oq-engine/openquake/calculators/event_based_risk.py", line 506, in save_results
    for dic in res:
  File "/usr/local/openquake/oq-hazardlib/openquake/baselib/parallel.py", line 397, in __iter__
    raise RuntimeError(val)
RuntimeError:
  File "/usr/local/openquake/oq-hazardlib/openquake/baselib/parallel.py", line 239, in safely_call
    got = func(*args)
  File "/usr/local/openquake/oq-engine/openquake/calculators/event_based_risk.py", line 172, in event_based_risk
    _aggregate(outputs, riskmodel, agg, ass, idx, result, monitor)
  File "/usr/local/openquake/oq-engine/openquake/calculators/event_based_risk.py", line 110, in _aggregate
    for outs in outputs:
  File "/usr/local/openquake/oq-engine/openquake/risklib/riskinput.py", line 447, in gen_outputs
    imt = riskmodel.risk_functions[lt].imt
KeyError: 'occupants'
[2017-03-03 21:30:49,585 #385 CRITICAL]
Traceback (most recent call last):
  File "/usr/local/openquake/oq-engine/openquake/calculators/base.py", line 196, in run
    self.pre_execute()
  File "/usr/local/openquake/oq-engine/openquake/calculators/base.py", line 431, in pre_execute
    self.precalc = (self.compute_previous() if precalc_id is None
  File "/usr/local/openquake/oq-engine/openquake/calculators/base.py", line 367, in compute_previous
    precalc.run(close=False)
  File "/usr/local/openquake/oq-engine/openquake/calculators/base.py", line 197, in run
    self.result = self.execute()
  File "/usr/local/openquake/oq-engine/openquake/calculators/event_based_risk.py", line 476, in execute
    num_events = self.save_results(allres, num_rlzs)
  File "/usr/local/openquake/oq-engine/openquake/calculators/event_based_risk.py", line 506, in save_results
    for dic in res:
  File "/usr/local/openquake/oq-hazardlib/openquake/baselib/parallel.py", line 397, in __iter__
    raise RuntimeError(val)
RuntimeError:
  File "/usr/local/openquake/oq-hazardlib/openquake/baselib/parallel.py", line 239, in safely_call
    got = func(*args)
  File "/usr/local/openquake/oq-engine/openquake/calculators/event_based_risk.py", line 172, in event_based_risk
    _aggregate(outputs, riskmodel, agg, ass, idx, result, monitor)
  File "/usr/local/openquake/oq-engine/openquake/calculators/event_based_risk.py", line 110, in _aggregate
    for outs in outputs:
  File "/usr/local/openquake/oq-engine/openquake/risklib/riskinput.py", line 447, in gen_outputs
    imt = riskmodel.risk_functions[lt].imt
KeyError: 'occupants'
[2017-03-03 21:30:49,716 #385 CRITICAL] Traceback (most recent call last):
  File "/usr/local/openquake/oq-engine/openquake/engine/engine.py", line 186, in run_calc
    _do_run_calc(calc, exports, hazard_calculation_id, **kw)
  File "/usr/local/openquake/oq-engine/openquake/engine/engine.py", line 219, in _do_run_calc
    close=False, **kw)  # don't close the datastore too soon
  File "/usr/local/openquake/oq-engine/openquake/calculators/base.py", line 196, in run
    self.pre_execute()
  File "/usr/local/openquake/oq-engine/openquake/calculators/base.py", line 431, in pre_execute
    self.precalc = (self.compute_previous() if precalc_id is None
  File "/usr/local/openquake/oq-engine/openquake/calculators/base.py", line 367, in compute_previous
    precalc.run(close=False)
  File "/usr/local/openquake/oq-engine/openquake/calculators/base.py", line 197, in run
    self.result = self.execute()
  File "/usr/local/openquake/oq-engine/openquake/calculators/event_based_risk.py", line 476, in execute
    num_events = self.save_results(allres, num_rlzs)
  File "/usr/local/openquake/oq-engine/openquake/calculators/event_based_risk.py", line 506, in save_results
    for dic in res:
  File "/usr/local/openquake/oq-hazardlib/openquake/baselib/parallel.py", line 397, in __iter__
    raise RuntimeError(val)
RuntimeError:
  File "/usr/local/openquake/oq-hazardlib/openquake/baselib/parallel.py", line 239, in safely_call
    got = func(*args)
  File "/usr/local/openquake/oq-engine/openquake/calculators/event_based_risk.py", line 172, in event_based_risk
    _aggregate(outputs, riskmodel, agg, ass, idx, result, monitor)
  File "/usr/local/openquake/oq-engine/openquake/calculators/event_based_risk.py", line 110, in _aggregate
    for outs in outputs:
  File "/usr/local/openquake/oq-engine/openquake/risklib/riskinput.py", line 447, in gen_outputs
    imt = riskmodel.risk_functions[lt].imt
KeyError: 'occupants'

Traceback (most recent call last):
  File "/usr/local/openquake/oq-engine/bin/oq", line 33, in <module>
    main.oq()
  File "/usr/local/openquake/oq-engine/openquake/commands/__main__.py", line 49, in oq
    parser.callfunc()
  File "/usr/local/openquake/oq-hazardlib/openquake/baselib/sap.py", line 186, in callfunc
    return self.func(**vars(namespace))
  File "/usr/local/openquake/oq-hazardlib/openquake/baselib/sap.py", line 245, in main
    return func(**kw)
  File "/usr/local/openquake/oq-engine/openquake/commands/engine.py", line 173, in engine
    exports, hazard_calculation_id=hc_id)
  File "/usr/local/openquake/oq-engine/openquake/commands/engine.py", line 64, in run_job
    hazard_calculation_id=hazard_calculation_id, **kw)
  File "/usr/local/openquake/oq-engine/openquake/engine/engine.py", line 186, in run_calc
    _do_run_calc(calc, exports, hazard_calculation_id, **kw)
  File "/usr/local/openquake/oq-engine/openquake/engine/engine.py", line 219, in _do_run_calc
    close=False, **kw)  # don't close the datastore too soon
  File "/usr/local/openquake/oq-engine/openquake/calculators/base.py", line 196, in run
    self.pre_execute()
  File "/usr/local/openquake/oq-engine/openquake/calculators/base.py", line 431, in pre_execute
    self.precalc = (self.compute_previous() if precalc_id is None
  File "/usr/local/openquake/oq-engine/openquake/calculators/base.py", line 367, in compute_previous
    precalc.run(close=False)
  File "/usr/local/openquake/oq-engine/openquake/calculators/base.py", line 197, in run
    self.result = self.execute()
  File "/usr/local/openquake/oq-engine/openquake/calculators/event_based_risk.py", line 476, in execute
    num_events = self.save_results(allres, num_rlzs)
  File "/usr/local/openquake/oq-engine/openquake/calculators/event_based_risk.py", line 506, in save_results
    for dic in res:
  File "/usr/local/openquake/oq-hazardlib/openquake/baselib/parallel.py", line 397, in __iter__
    raise RuntimeError(val)
RuntimeError:
  File "/usr/local/openquake/oq-hazardlib/openquake/baselib/parallel.py", line 239, in safely_call
    got = func(*args)
  File "/usr/local/openquake/oq-engine/openquake/calculators/event_based_risk.py", line 172, in event_based_risk
    _aggregate(outputs, riskmodel, agg, ass, idx, result, monitor)
  File "/usr/local/openquake/oq-engine/openquake/calculators/event_based_risk.py", line 110, in _aggregate
    for outs in outputs:
  File "/usr/local/openquake/oq-engine/openquake/risklib/riskinput.py", line 447, in gen_outputs
    imt = riskmodel.risk_functions[lt].imt
KeyError: 'occupants'
```

**Comment by micheles** [comment]
The issue is that for taxonomy `S1M_MC` there is a vulnerability function only for structural, not for occupants. I will change the calculator so that a clear error message is displayed at the beginning, before even starting the calculation.
