### ISSUE TITLE
Run risk is broken in the WebUI

### ISSUE THREAD

**Issue by daniviga** [gem/oq-engine#2682]
When running a risk demo via the WebUI (anyone has job_hazard.ini + job_risk.ini):
- Hazard works fine
- Running risk the following error is raised:

```python
[2017-03-30 18:43:06,097 #2 CRITICAL] Traceback (most recent call last):
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/engine/engine.py", line 186, in run_calc
    _do_run_calc(calc, exports, hazard_calculation_id, **kw)
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/engine/engine.py", line 219, in _do_run_calc
    close=False, **kw)  # don't close the datastore too soon
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/calculators/base.py", line 196, in run
    self.pre_execute()
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/calculators/scenario_damage.py", line 142, in pre_execute
    base.RiskCalculator.pre_execute(self)
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/calculators/base.py", line 432, in pre_execute
    else self.read_previous(precalc_id))
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/calculators/base.py", line 377, in read_previous
    parent = datastore.read(precalc_id)
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/commonlib/datastore.py", line 124, in read
    if calc_id < 0:  # retrieve an old datastore
TypeError: unorderable types: str() < int()
```

The error was already there in engine-2.3

**Comment by micheles** [comment]
This is a Python 3 bug. In Python 2 unorderable types are unfortunately orderable. This is easy to fix, though.
