### ISSUE TITLE
numpy error in the disaggregation converter

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#2702]
Here is the error submitted by an user:

```python
caristizabal@oats3:~/Ensayo$ python disaggregation_converter.py --plot --input-file disaggregation.xml --output-dit output
Traceback (most recent call last):
  File "disaggregation_converter.py", line 48, in <module>
    import numpy
  File "/opt/openquake/lib/python3.5/site-packages/numpy/__init__.py", line 180, in <module>
    from . import add_newdocs
  File "/opt/openquake/lib/python3.5/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/opt/openquake/lib/python3.5/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/opt/openquake/lib/python3.5/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/opt/openquake/lib/python3.5/site-packages/numpy/core/__init__.py", line 14, in <module>
    from . import multiarray
ImportError: cannot import name multiarray
```

The `nrml_converters` are obsolete and should be removed from OATS, however this error should still be in the engine since the code has been moved there. Googling for this error returns a lot of answers, it looks like a common problem.

**Comment by daniviga** [comment]
nrml_converters aren't installed on OATS3 since long time ago. The user has downloaded her own copy.
