### ISSUE TITLE
Another `oq export hcurves-rlzs -e hdf5` bug

### ISSUE THREAD

**Issue by micheles** [gem/oq-engine#2851]
If the .hdf5 file is already there, a strange error is generated, as discovered by M. Pagani:
```
INFO:root:Reading 47.66 MB of probability maps
INFO:root:Building the hazard curves for 2579 sites, 16 rlzs
INFO:root:Starting 16 tasks
Traceback (most recent call last):
  File "/usr/local/openquake/oq-engine/bin/oq", line 35, in <module>
    main.oq()
  File "/usr/local/openquake/oq-engine/openquake/commands/__main__.py", line 49, in oq
    parser.callfunc()
  File "/usr/local/openquake/oq-hazardlib/openquake/baselib/sap.py", line 186, in callfunc
    return self.func(**vars(namespace))
  File "/usr/local/openquake/oq-hazardlib/openquake/baselib/sap.py", line 245, in main
    return func(**kw)
  File "/usr/local/openquake/oq-engine/openquake/commands/export.py", line 42, in export
    fnames = export_((datastore_key, fmt), dstore)
  File "/usr/local/openquake/oq-hazardlib/openquake/baselib/general.py", line 504, in __call__
    return self[key](obj, *args, **kw)
  File "/usr/local/openquake/oq-engine/openquake/calculators/export/hazard.py", line 393, in export_hcurves_rlzs
    for sids, allcurves in parallel.Processmap(build_hcurves, allargs):
  File "/usr/local/openquake/oq-hazardlib/openquake/baselib/parallel.py", line 745, in __iter__
    for res in self.submit_all():
  File "/usr/local/openquake/oq-hazardlib/openquake/baselib/parallel.py", line 403, in __iter__
    raise RuntimeError(val)
RuntimeError: 
  File "/usr/local/openquake/oq-hazardlib/openquake/baselib/parallel.py", line 240, in safely_call
    got = func(*args)
  File "/usr/local/openquake/oq-engine/openquake/calculators/export/hazard.py", line 350, in build_hcurves
    pmaps = getter.get_pmaps(getter.sids)
  File "/usr/local/openquake/oq-engine/openquake/commonlib/calc.py", line 135, in get_pmaps
    return self.combine_pmaps(self.get_pmap_by_grp(sids))
  File "/usr/local/openquake/oq-engine/openquake/commonlib/calc.py", line 145, in get_pmap_by_grp
    sid2idx = {sid: i for i, sid in enumerate(dset.attrs['sids'])}
AttributeError: 'NoneType' object has no attribute 'attrs'
```
The file should be overridden instead.

**Comment by micheles** [comment]
I cannot reproduce the bug with the current code.
