### ISSUE TITLE
Newer numpy is now supported in the HMTK

### ISSUE THREAD

**Issue by daniviga** [gem/oq-engine#2974]
Following https://github.com/gem/oq-engine/pull/2967 `numpy` > 1.11 is now supported in the HMTK.

We need to update the changelog too (credits to @g-weatherill).

**Comment by daniviga** [comment]
With `numpy==1.13` I still get some failing tests:

```======================================================================
ERROR: Basic test of the entire completeness analysis using a synthetic
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/openquake/oq-engine/openquake/hmtk/tests/seismicity/completeness/comp_stepp1971_test.py", line 301, in test_complete_stepp_analysis_basic
    self.process.completeness(self.catalogue, self.config))
  File "<decorator-gen-4>", line 2, in completeness
  File "/home/openquake/oq-engine/openquake/hmtk/registry.py", line 110, in caller
    return fn(obj, catalogue, config, *args, **kwargs)
  File "/home/openquake/oq-engine/openquake/hmtk/seismicity/completeness/comp_stepp_1971.py", line 183, in completeness
    n_times))
  File "/home/openquake/oq-engine/openquake/hmtk/seismicity/completeness/comp_stepp_1971.py", line 343, in get_completeness_points
    np.log10(sigma[id0, iloc]))
  File "/home/openquake/oq-engine/openquake/hmtk/seismicity/completeness/comp_stepp_1971.py", line 373, in _fit_bilinear_to_stepp
    x_0 = [-1.0, xdata[len(xdata) / 2], xdata[0]]
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

======================================================================
ERROR: Tests the function get_completeness_points using a synthetic
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/openquake/oq-engine/openquake/hmtk/tests/seismicity/completeness/comp_stepp1971_test.py", line 269, in test_get_completeness_points
    ntime)
  File "/home/openquake/oq-engine/openquake/hmtk/seismicity/completeness/comp_stepp_1971.py", line 343, in get_completeness_points
    np.log10(sigma[id0, iloc]))
  File "/home/openquake/oq-engine/openquake/hmtk/seismicity/completeness/comp_stepp_1971.py", line 373, in _fit_bilinear_to_stepp
    x_0 = [-1.0, xdata[len(xdata) / 2], xdata[0]]
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

======================================================================
ERROR: Testing the Gardner and Knopoff algorithm
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/openquake/oq-engine/openquake/hmtk/tests/seismicity/declusterer/dec_gardner_knopoff_test.py", line 85, in test_dec_gardner_knopoff
    vcl, flagvector = dec.decluster(self.cat, config)
  File "<decorator-gen-3>", line 2, in decluster
  File "/home/openquake/oq-engine/openquake/hmtk/registry.py", line 110, in caller
    return fn(obj, catalogue, config, *args, **kwargs)
  File "/home/openquake/oq-engine/openquake/hmtk/seismicity/declusterer/dec_gardner_knopoff.py", line 137, in decluster
    vsel[vsel] = vsel1
TypeError: NumPy boolean array indexing assignment requires a 0 or 1-dimensional input, input has 2 dimensions

======================================================================
FAIL: test (openquake.commonlib.tests.readinput_test.TestLoadCurvesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/openquake/oq-engine/openquake/commonlib/tests/readinput_test.py", line 715, in test
    ([0.98728, 0.98266, 0.94957], [0.98728, 0.98226, 0.94947, 0.92947])]''')
AssertionError: '[ ([ 0.098727,  0.098265,  0.094956], [ 0.[122 chars] ])]' != '[([0.098727, 0.098265, 0.094956], [0.09872[100 chars]7])]'
- [ ([ 0.098727,  0.098265,  0.094956], [ 0.098728,  0.098216,  0.094945,  0.092947])
?  -  -          -         -             -          -          -         -
+ [([0.098727, 0.098265, 0.094956], [0.098728, 0.098216, 0.094945, 0.092947])
-  ([ 0.98728 ,  0.98266 ,  0.94957 ], [ 0.98728 ,  0.98226 ,  0.94947 ,  0.92947 ])]?    -       - -        - -        -    -       - -        - -        - -        -
+  ([0.98728, 0.98266, 0.94957], [0.98728, 0.98226, 0.94947, 0.92947])]
-------------------- >> begin captured logging << --------------------
[2017-08-10 08:56:18,954 #467 DEBUG] /tmp/tmpkwhh9dlh.xml is at an outdated version: http://openquake.org/xmlns/nrml/0.4
--------------------- >> end captured logging << ---------------------
```

**Comment by g-weatherill** [comment]
I will open a PR to fix the hmtk errors. The last failure I don't know the cause of.

**Comment by micheles** [comment]
The last failure is because numpy 1.13 changed the string representation of arrays by adding spaces.
Before it was
```
[([0.098727, 0.098265, 0.094956], [0.098728, 0.098216, 0.094945, 0.092947])
 ([0.98728, 0.98266, 0.94957], [0.98728, 0.98226, 0.94947, 0.92947])]'
```
now it is
```
[ ([ 0.098727,  0.098265,  0.094956], [ 0.098728,  0.098216,  0.094945,  0.092947])
 ([ 0.98728 ,  0.98266 ,  0.94957 ], [ 0.98728 ,  0.98226 ,  0.94947 ,  0.92947 ])]
```
The solution is to change the tests so that it does not depend on the string representation of the arrays. I will do that in a PR.
