### ISSUE TITLE
oq reset fails

### ISSUE THREAD

**Issue by daniviga** [gem/oq-engine#3207]
```python
(py35) Jenkinss-MacBook-Pro:~ jenkins$ oq reset  -y
dbserver stopped
Removed /Users/jenkins/oqdata/db.sqlite3
WARNING:root:DB server stopped
Removed /Users/jenkins/oqdata
Traceback (most recent call last):
  File "/Users/jenkins/GIT/oq-engine/openquake/server/dbapi.py", line 302, in conn
    return self.local.conn
AttributeError: '_thread._local' object has no attribute 'conn'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jenkins/py35/bin/oq", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/jenkins/GIT/oq-engine/bin/oq", line 35, in <module>
    main.oq()
  File "/Users/jenkins/GIT/oq-engine/openquake/commands/__main__.py", line 46, in oq
    parser.callfunc()
  File "/Users/jenkins/GIT/oq-engine/openquake/baselib/sap.py", line 186, in callfunc
    return self.func(**vars(namespace))
  File "/Users/jenkins/GIT/oq-engine/openquake/baselib/sap.py", line 245, in main
    return func(**kw)
  File "/Users/jenkins/GIT/oq-engine/openquake/commands/dbserver.py", line 47, in dbserver
    dbs.run_server(dbpath, dbhostport)
  File "/Users/jenkins/GIT/oq-engine/openquake/baselib/sap.py", line 115, in __call__
    return self.func(*args)
  File "/Users/jenkins/GIT/oq-engine/openquake/server/dbserver.py", line 205, in run_server
    dbs.stop()
  File "/Users/jenkins/GIT/oq-engine/openquake/server/dbserver.py", line 117, in stop
    self.db.close()
  File "/Users/jenkins/GIT/oq-engine/openquake/server/dbapi.py", line 375, in close
    self.conn.close()
  File "/Users/jenkins/GIT/oq-engine/openquake/server/dbapi.py", line 304, in conn
    self.local.conn = self.connect(*self.args, **self.kw)
sqlite3.OperationalError: unable to open database file
```

That's why Jenkins is almost always broken since the last merges. It can be reproduced on Linux too.

**Comment by daniviga** [comment]
It looks like that the stop is (SIGTERM) is performed asynchronously and the dbserver si not fully stopped when we try to delete the `oqdata` dir

**Comment by daniviga** [comment]
Closed via https://github.com/gem/oq-engine/pull/3209
