### ISSUE TITLE
MultiPointSource doesn't work with to_shapefile option

### ISSUE THREAD

**Issue by klunk386** [gem/oq-engine#3288]
An xml source model using MultiPointSource cannot be converted to a shapefile using the _to_shapefile_ option as the source type is not recognised:
```
Extracting GridMultiSources_S50_ files
Traceback (most recent call last):
  File "/home/openquake/GEM/.env/py27/bin/oq", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/openquake/GEM/oq-engine/bin/oq", line 35, in <module>
    main.oq()
  File "/home/openquake/GEM/oq-engine/openquake/commands/__main__.py", line 46, in oq
    parser.callfunc()
  File "/home/openquake/GEM/oq-engine/openquake/baselib/sap.py", line 186, in callfunc
    return self.func(**vars(namespace))
  File "/home/openquake/GEM/oq-engine/openquake/baselib/sap.py", line 245, in main
    return func(**kw)
  File "/home/openquake/GEM/oq-engine/openquake/commands/to_shapefile.py", line 41, in to_shapefile
    shapefileparser.ShapefileParser().write(output, source_model)
  File "/home/openquake/GEM/oq-engine/openquake/commonlib/shapefileparser.py", line 1090, in write
    % src.tag)
ValueError: Source type {http://openquake.org/xmlns/nrml/0.5}multiPointSource not recognized
```

**Comment by micheles** [comment]
This has been blocked for 2+ years because supporting shapefiles is not worth the effort. Instead, we should deprecate the shapefile converters and introduce new converter to and from the geopackage format, that can be generated in Python via fiona and easily managed with QGIS.
