### ISSUE TITLE
Possible circular import

### ISSUE THREAD

**Issue by daniviga** [gem/oq-engine#3879]
On a machine I'm not able to run `oq` because of this error:

```python
Traceback (most recent call last):                                                                      
  File "/opt/openquake/bin/oq", line 11, in <module>                                                    
    load_entry_point('openquake.engine', 'console_scripts', 'oq')()                                     
  File "/opt/openquake/src/oq-engine/openquake/commands/__main__.py", line 48, in oq                    
    importlib.import_module(modname)                                                                    
  File "/opt/python36/lib/python3.6/importlib/__init__.py", line 126, in import_module                  
    return _bootstrap._gcd_import(name[level:], package, level)                                         
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import                                        
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load                                     
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked                            
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked                                     
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module                               
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed                          
  File "/opt/openquake/src/oq-engine/openquake/commands/show.py", line 29, in <module>                  
    from openquake.calculators import getters                                                           
  File "/opt/openquake/src/oq-engine/openquake/calculators/__init__.py", line 23, in <module>           
    import_all('openquake.calculators')                                                                 
  File "/opt/openquake/src/oq-engine/openquake/baselib/general.py", line 456, in import_all             
    importlib.import_module(modname)                                                                    
  File "/opt/python36/lib/python3.6/importlib/__init__.py", line 126, in import_module                  
    return _bootstrap._gcd_import(name[level:], package, level)                                         
  File "/opt/openquake/src/oq-engine/openquake/calculators/extract.py", line 34, in <module>            
    from openquake.calculators.export.loss_curves import get_loss_builder                               
  File "/opt/openquake/src/oq-engine/openquake/calculators/export/__init__.py", line 66, in <module>    
    import_all('openquake.calculators.export')                                                          
  File "/opt/openquake/src/oq-engine/openquake/baselib/general.py", line 456, in import_all             
    importlib.import_module(modname)                                                                    
  File "/opt/python36/lib/python3.6/importlib/__init__.py", line 126, in import_module                  
    return _bootstrap._gcd_import(name[level:], package, level)                                         
  File "/opt/openquake/src/oq-engine/openquake/calculators/export/__init__.py", line 66, in <module>    
    import_all('openquake.calculators.export')                                                          
  File "/opt/openquake/src/oq-engine/openquake/baselib/general.py", line 456, in import_all             
    importlib.import_module(modname)                                                                    
  File "/opt/python36/lib/python3.6/importlib/__init__.py", line 126, in import_module                  
    return _bootstrap._gcd_import(name[level:], package, level)                                         
  File "/opt/openquake/src/oq-engine/openquake/calculators/export/hazard.py", line 33, in <module>      
    from openquake.calculators.extract import extract, get_mesh                                         
ImportError: cannot import name 'extract'                                                               
```

When trying to import `openquake.calculators` I get

```ipython
In [1]: import openquake.calculators
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-23bab5add1fe> in <module>()
----> 1 import openquake.calculators

/opt/openquake/src/oq-engine/openquake/calculators/__init__.py in <module>()
     21 
     22 # make sure the `base,calculators` dictionary is populated
---> 23 import_all('openquake.calculators')
     24 
     25 # import the development packages if any

/opt/openquake/src/oq-engine/openquake/baselib/general.py in import_all(module_or_package)
    454                 modname = (module_or_package + cwd[n:].replace(os.sep, '.') +
    455                            '.' + os.path.basename(f[:-3]))
--> 456                 importlib.import_module(modname)
    457     return set(sys.modules) - already_imported
    458 

/opt/python36/lib/python3.6/importlib/__init__.py in import_module(name, package)
    124                 break
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 
    128 

/opt/openquake/src/oq-engine/openquake/calculators/extract.py in <module>()
     32 from openquake.baselib.python3compat import encode
     33 from openquake.calculators import getters
---> 34 from openquake.calculators.export.loss_curves import get_loss_builder
     35 from openquake.commonlib import calc, util
     36 

/opt/openquake/src/oq-engine/openquake/calculators/export/__init__.py in <module>()
     64 export.from_db = False  # overridden when exporting from db
     65 
---> 66 import_all('openquake.calculators.export')
     67 
     68 

/opt/openquake/src/oq-engine/openquake/baselib/general.py in import_all(module_or_package)
    454                 modname = (module_or_package + cwd[n:].replace(os.sep, '.') +
    455                            '.' + os.path.basename(f[:-3]))
--> 456                 importlib.import_module(modname)
    457     return set(sys.modules) - already_imported
    458 

/opt/python36/lib/python3.6/importlib/__init__.py in import_module(name, package)
    124                 break
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 
    128 

/opt/openquake/src/oq-engine/openquake/calculators/export/__init__.py in <module>()
     64 export.from_db = False  # overridden when exporting from db
     65 
---> 66 import_all('openquake.calculators.export')
     67 
     68 

/opt/openquake/src/oq-engine/openquake/baselib/general.py in import_all(module_or_package)
    454                 modname = (module_or_package + cwd[n:].replace(os.sep, '.') +
    455                            '.' + os.path.basename(f[:-3]))
--> 456                 importlib.import_module(modname)
    457     return set(sys.modules) - already_imported
    458 

/opt/python36/lib/python3.6/importlib/__init__.py in import_module(name, package)
    124                 break
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 
    128 

/opt/openquake/src/oq-engine/openquake/calculators/export/hazard.py in <module>()
     31 from openquake.hazardlib.calc import disagg
     32 from openquake.calculators.views import view
---> 33 from openquake.calculators.extract import extract, get_mesh
     34 from openquake.calculators.export import export
     35 from openquake.calculators.getters import (

ImportError: cannot import name 'extract'
```

but if I try again just after the error it works

```python
In [2]: import openquake.calculators

In [3]: openquake.calculators.__init__
Out[3]: <module 'openquake.calculators.__init__' from '/opt/openquake/src/oq-engine/openquake/calculators/__init__.py'>
```

It looks like that `calculators` loads `extract` which loads `export` which again loads `extract`.
This issue is always reproducible on that specific machine using a clean installation in a venv.

**Comment by daniviga** [comment]
It looks like one of the causes is `import_all('openquake.calculators.export')` in `openquake/calculators/export/__init__.py` which is called by `extract` but tries to load `exctract` too because of `openquake/calculators/export/hazard.py`
