### ISSUE TITLE
OverflowError: cannot serialize a bytes object larger than 4 GiB

### ISSUE THREAD

**Issue by daniviga** [gem/oq-engine#3882]
```python
[2018-07-25 15:00:02,656: ERROR/ForkPoolWorker-18] Task openquake.baselib.parallel.safely_call[416f129f-6d19-4b79-a794-b849e3506425] raised unexpected: OverflowError('cannot serialize a bytes object larger than 4 GiB',)
Traceback (most recent call last):
  File "/opt/openquake/lib/python3.6/site-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/openquake/lib/python3.6/site-packages/celery/app/trace.py", line 629, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/openquake/oq-engine/openquake/baselib/parallel.py", line 366, in safely_call
    zsocket.send(res)
  File "/opt/openquake/oq-engine/openquake/baselib/zeromq.py", line 148, in send
    self.zsocket.send_pyobj(obj)
  File "/opt/openquake/lib/python3.6/site-packages/zmq/sugar/socket.py", line 601, in send_pyobj
    msg = pickle.dumps(obj, protocol)
OverflowError: cannot serialize a bytes object larger than 4 GiB
```

This happened with an hazard calculation for Chile and it happened on two nodes out of five.
I see two issues here: one is the error above, the second one is that the error _was not_ propagated to master and the computation is left to an 'executing' state forever.

We should at least fix the error propagation.

/cc @CatalinaYepes

**Comment by micheles** [comment]
The error propagation can be fixed, the underlying error no. The only solution is to raise concurrent_tasks and hope for the best (in the case of Chile I have little hope, though).

**Comment by CatalinaYepes** [comment]
Indeed the problem was the concurrent_task parameter. I run the same calculation, setting `concurrent_tasks=2000` and it run without problems
