### ISSUE TITLE
Test in hazardlib/tests/geo/surface/base_surface_test.py are not executed (and some are broken)

### ISSUE THREAD

**Issue by daniviga** [gem/oq-engine#3891]
Such test has a very strange behavior (discovered in #3890):

when running `nosetests -vsx openquake/hazardlib/tests/geo/surface` all tests pass:

```
Ran 116 tests in 0.377s

OK
```

when running `nosetests -sx openquake/hazardlib/tests/geo/surface/base_surface_test.py` a test fails

```
======================================================================
FAIL: test_point_outside (openquake.hazardlib.tests.geo.surface.base_surface_test.GetJoynerBooreDistanceTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/hazardlib/tests/geo/surface/base_surface_test.py", line 117, in test_point_outside
    self.assertTrue(numpy.allclose(dists, expected_dists, atol=0.2))
AssertionError: False is not true
----------------------------------------------------------------------
Ran 7 tests in 0.008s

FAILED (failures=1)
```

and when the file `openquake/hazardlib/geo/surface/base.py` is marked as non executable (as it should be, it has no `__main__` neither a shebang) it always fails (also in the first case above):

```bash
chmod -x openquake/hazardlib/tests/geo/surface/base_surface_test.py
$ nosetests -sx openquake/hazardlib/tests/geo/surface/
======================================================================
FAIL: test_point_outside (openquake.hazardlib.tests.geo.surface.base_surface_test.GetJoynerBooreDistanceTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/hazardlib/tests/geo/surface/base_surface_test.py", line 117, in test_point_outside
    self.assertTrue(numpy.allclose(dists, expected_dists, atol=0.2))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 7 tests in 0.009s

FAILED (failures=1)
```

**Comment by daniviga** [comment]
I just discovered, uning pdb, that tests in `base_surface_test.py` that file are not executed (and 4 of them are actually *broken*) when `nosetests -s openquake/hazardlib/tests/geo/surface/` is run and `openquake/hazardlib/tests/geo/surface/base_surface_test.py` is marked as executable.

It looks like that `nose` is not recognizing that file if it's marked as executable:

```bash
$ chmod +x openquake/hazardlib/tests/geo/surface/base_surface_test.py # as it's in master
$ nosetests -s openquake/hazardlib/tests/geo/surface/
Ran 116 tests in 0.370s

OK
```

```bash
$ chmod -x openquake/hazardlib/tests/geo/surface/base_surface_test.py # as it should be
$ nosetests -s openquake/hazardlib/tests/geo/surface/
......F..F.FF......................................................................................................................................
======================================================================
FAIL: test_point_outside (openquake.hazardlib.tests.geo.surface.base_surface_test.GetJoynerBooreDistanceTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/hazardlib/tests/geo/surface/base_surface_test.py", line 117, in test_point_outside
    self.assertTrue(numpy.allclose(dists, expected_dists, atol=0.2))
AssertionError: False is not true

======================================================================
FAIL: test_2 (openquake.hazardlib.tests.geo.surface.base_surface_test.GetMinDistanceTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/hazardlib/tests/geo/surface/base_surface_test.py", line 59, in test_2
    places=4)
AssertionError: 40.1213468 != 40.09707543926494 within 4 places

======================================================================
FAIL: test_4 (openquake.hazardlib.tests.geo.surface.base_surface_test.GetMinDistanceTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/hazardlib/tests/geo/surface/base_surface_test.py", line 72, in test_4
    places=4)
AssertionError: 55.6159556 != 55.58568426746575 within 4 places

======================================================================
FAIL: test_several_sites (openquake.hazardlib.tests.geo.surface.base_surface_test.GetMinDistanceTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/hazardlib/tests/geo/surface/base_surface_test.py", line 79, in test_several_sites
    self.assertTrue(numpy.allclose(dists, expected_dists))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 147 tests in 0.376s

FAILED (failures=4)

```

You can see that in the first case (current master) 31 tests are not executed (116 vs 147).

**Comment by micheles** [comment]
I see. It looks like a bug in nose that was not running those tests. The reason the numbers are different is that some time ago I changed the distance algorithm (we use scipy.distance now). Just replace the wrong expected distances with the right distances.
BTW, today I discovered the numpy has abandoned nose because nose is abandonware (pun intended).
We may think about abandoning nose in the future. Since we are using Python 3 now, the unittest module has new discovery features that should make nose unneeded. This is something to investigate.

**Comment by daniviga** [comment]
The same issue affects `./openquake/hazardlib/tests/geo/surface/multi_test.py`. In total there are 17 errors and 4 failures:

```bash
$ nosetests -s openquake.hazardlib.tests.geo.surface
......F..F.FF..............................................................EEEEEEEEEEEEEEEEE..............................................................................
======================================================================
ERROR: test_get_closest_points_mesh1D (openquake.hazardlib.tests.geo.surface.multi_test.DistancesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/hazardlib/tests/geo/surface/multi_test.py", line 155, in test_get_closest_points_mesh1D
    surf = MultiSurface(self.surfaces_mesh1D)
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/hazardlib/geo/surface/multi.py", line 124, in __init__
    self.edge_set = self._get_edge_set(tol)
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/hazardlib/geo/surface/multi.py", line 158, in _get_edge_set
    raise ValueError("Surface %s not recognised" % str(surface))
ValueError: Surface <openquake.hazardlib.tests.geo.surface.multi_test._BaseMultiTestCase.FakeSurface object at 0x7f0127b22048> not recognised

======================================================================
ERROR: test_get_closest_points_mesh2D (openquake.hazardlib.tests.geo.surface.multi_test.DistancesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/hazardlib/tests/geo/surface/multi_test.py", line 139, in test_get_closest_points_mesh2D
    surf = MultiSurface(self.surfaces_mesh2D)
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/hazardlib/geo/surface/multi.py", line 124, in __init__
    self.edge_set = self._get_edge_set(tol)
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/hazardlib/geo/surface/multi.py", line 158, in _get_edge_set
    raise ValueError("Surface %s not recognised" % str(surface))
ValueError: Surface <openquake.hazardlib.tests.geo.surface.multi_test._BaseMultiTestCase.FakeSurface object at 0x7f0127b22128> not recognised

======================================================================
ERROR: test_joyner_boore_distance_mesh1D (openquake.hazardlib.tests.geo.surface.multi_test.DistancesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/hazardlib/tests/geo/surface/multi_test.py", line 176, in test_joyner_boore_distance_mesh1D
    surf = MultiSurface(self.surfaces_mesh1D)
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/hazardlib/geo/surface/multi.py", line 124, in __init__
    self.edge_set = self._get_edge_set(tol)
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/hazardlib/geo/surface/multi.py", line 158, in _get_edge_set
    raise ValueError("Surface %s not recognised" % str(surface))
ValueError: Surface <openquake.hazardlib.tests.geo.surface.multi_test._BaseMultiTestCase.FakeSurface object at 0x7f0127b22be0> not recognised

======================================================================
ERROR: test_joyner_boore_distance_mesh2D (openquake.hazardlib.tests.geo.surface.multi_test.DistancesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/hazardlib/tests/geo/surface/multi_test.py", line 171, in test_joyner_boore_distance_mesh2D
    surf = MultiSurface(self.surfaces_mesh2D)
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/hazardlib/geo/surface/multi.py", line 124, in __init__
    self.edge_set = self._get_edge_set(tol)
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/hazardlib/geo/surface/multi.py", line 158, in _get_edge_set
    raise ValueError("Surface %s not recognised" % str(surface))
ValueError: Surface <openquake.hazardlib.tests.geo.surface.multi_test._BaseMultiTestCase.FakeSurface object at 0x7f0127b1c080> not recognised

======================================================================
ERROR: test_min_distance_mesh1D (openquake.hazardlib.tests.geo.surface.multi_test.DistancesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/hazardlib/tests/geo/surface/multi_test.py", line 134, in test_min_distance_mesh1D
    surf = MultiSurface(self.surfaces_mesh1D)
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/hazardlib/geo/surface/multi.py", line 124, in __init__
    self.edge_set = self._get_edge_set(tol)
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/hazardlib/geo/surface/multi.py", line 158, in _get_edge_set
    raise ValueError("Surface %s not recognised" % str(surface))
ValueError: Surface <openquake.hazardlib.tests.geo.surface.multi_test._BaseMultiTestCase.FakeSurface object at 0x7f0127b1c320> not recognised

======================================================================
ERROR: test_min_distance_mesh2D (openquake.hazardlib.tests.geo.surface.multi_test.DistancesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/hazardlib/tests/geo/surface/multi_test.py", line 129, in test_min_distance_mesh2D
    surf = MultiSurface(self.surfaces_mesh2D)
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/hazardlib/geo/surface/multi.py", line 124, in __init__
    self.edge_set = self._get_edge_set(tol)
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/hazardlib/geo/surface/multi.py", line 158, in _get_edge_set
    raise ValueError("Surface %s not recognised" % str(surface))
ValueError: Surface <openquake.hazardlib.tests.geo.surface.multi_test._BaseMultiTestCase.FakeSurface object at 0x7f0127b1c390> not recognised

======================================================================
ERROR: test_rx_distance_mesh1D (openquake.hazardlib.tests.geo.surface.multi_test.DistancesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/hazardlib/tests/geo/surface/multi_test.py", line 186, in test_rx_distance_mesh1D
    surf = MultiSurface(self.surfaces_mesh1D)
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/hazardlib/geo/surface/multi.py", line 124, in __init__
    self.edge_set = self._get_edge_set(tol)
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/hazardlib/geo/surface/multi.py", line 158, in _get_edge_set
    raise ValueError("Surface %s not recognised" % str(surface))
ValueError: Surface <openquake.hazardlib.tests.geo.surface.multi_test._BaseMultiTestCase.FakeSurface object at 0x7f0127b1c630> not recognised

======================================================================
ERROR: test_rx_distance_mesh2D (openquake.hazardlib.tests.geo.surface.multi_test.DistancesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/hazardlib/tests/geo/surface/multi_test.py", line 181, in test_rx_distance_mesh2D
    surf = MultiSurface(self.surfaces_mesh2D)
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/hazardlib/geo/surface/multi.py", line 124, in __init__
    self.edge_set = self._get_edge_set(tol)
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/hazardlib/geo/surface/multi.py", line 158, in _get_edge_set
    raise ValueError("Surface %s not recognised" % str(surface))
ValueError: Surface <openquake.hazardlib.tests.geo.surface.multi_test._BaseMultiTestCase.FakeSurface object at 0x7f0127b1c7f0> not recognised

======================================================================
ERROR: test_ry0_distance_mesh1D (openquake.hazardlib.tests.geo.surface.multi_test.DistancesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/hazardlib/tests/geo/surface/multi_test.py", line 191, in test_ry0_distance_mesh1D
    surf = MultiSurface(self.surfaces_mesh1D)
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/hazardlib/geo/surface/multi.py", line 124, in __init__
    self.edge_set = self._get_edge_set(tol)
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/hazardlib/geo/surface/multi.py", line 158, in _get_edge_set
    raise ValueError("Surface %s not recognised" % str(surface))
ValueError: Surface <openquake.hazardlib.tests.geo.surface.multi_test._BaseMultiTestCase.FakeSurface object at 0x7f0127b1cac8> not recognised

======================================================================
ERROR: test_area (openquake.hazardlib.tests.geo.surface.multi_test.SurfacePropertiesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/hazardlib/tests/geo/surface/multi_test.py", line 214, in test_area
    surf = MultiSurface(self.surfaces_mesh2D)
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/hazardlib/geo/surface/multi.py", line 124, in __init__
    self.edge_set = self._get_edge_set(tol)
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/hazardlib/geo/surface/multi.py", line 158, in _get_edge_set
    raise ValueError("Surface %s not recognised" % str(surface))
ValueError: Surface <openquake.hazardlib.tests.geo.surface.multi_test._BaseMultiTestCase.FakeSurface object at 0x7f0127b1cba8> not recognised

======================================================================
ERROR: test_bounding_box (openquake.hazardlib.tests.geo.surface.multi_test.SurfacePropertiesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/hazardlib/tests/geo/surface/multi_test.py", line 218, in test_bounding_box
    surf = MultiSurface(self.surfaces_mesh2D)
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/hazardlib/geo/surface/multi.py", line 124, in __init__
    self.edge_set = self._get_edge_set(tol)
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/hazardlib/geo/surface/multi.py", line 158, in _get_edge_set
    raise ValueError("Surface %s not recognised" % str(surface))
ValueError: Surface <openquake.hazardlib.tests.geo.surface.multi_test._BaseMultiTestCase.FakeSurface object at 0x7f0127b1ce48> not recognised

======================================================================
ERROR: test_get_dip (openquake.hazardlib.tests.geo.surface.multi_test.SurfacePropertiesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/hazardlib/tests/geo/surface/multi_test.py", line 206, in test_get_dip
    surf = MultiSurface(self.surfaces_mesh2D)
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/hazardlib/geo/surface/multi.py", line 124, in __init__
    self.edge_set = self._get_edge_set(tol)
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/hazardlib/geo/surface/multi.py", line 158, in _get_edge_set
    raise ValueError("Surface %s not recognised" % str(surface))
ValueError: Surface <openquake.hazardlib.tests.geo.surface.multi_test._BaseMultiTestCase.FakeSurface object at 0x7f0127b1cc50> not recognised

======================================================================
ERROR: test_get_strike (openquake.hazardlib.tests.geo.surface.multi_test.SurfacePropertiesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/hazardlib/tests/geo/surface/multi_test.py", line 202, in test_get_strike
    surf = MultiSurface(self.surfaces_mesh2D)
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/hazardlib/geo/surface/multi.py", line 124, in __init__
    self.edge_set = self._get_edge_set(tol)
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/hazardlib/geo/surface/multi.py", line 158, in _get_edge_set
    raise ValueError("Surface %s not recognised" % str(surface))
ValueError: Surface <openquake.hazardlib.tests.geo.surface.multi_test._BaseMultiTestCase.FakeSurface object at 0x7f0127b27eb8> not recognised

======================================================================
ERROR: test_get_width (openquake.hazardlib.tests.geo.surface.multi_test.SurfacePropertiesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/hazardlib/tests/geo/surface/multi_test.py", line 210, in test_get_width
    surf = MultiSurface(self.surfaces_mesh2D)
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/hazardlib/geo/surface/multi.py", line 124, in __init__
    self.edge_set = self._get_edge_set(tol)
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/hazardlib/geo/surface/multi.py", line 158, in _get_edge_set
    raise ValueError("Surface %s not recognised" % str(surface))
ValueError: Surface <openquake.hazardlib.tests.geo.surface.multi_test._BaseMultiTestCase.FakeSurface object at 0x7f0127b27470> not recognised

======================================================================
ERROR: test_middle_point_multi_surfaces (openquake.hazardlib.tests.geo.surface.multi_test.SurfacePropertiesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/hazardlib/tests/geo/surface/multi_test.py", line 235, in test_middle_point_multi_surfaces
    Point(0.0, -1.0, 10.0)),
TypeError: __init__() takes 7 positional arguments but 8 were given

======================================================================
ERROR: test_middle_point_single_surface (openquake.hazardlib.tests.geo.surface.multi_test.SurfacePropertiesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/hazardlib/tests/geo/surface/multi_test.py", line 226, in test_middle_point_single_surface
    surf = MultiSurface([self.surfaces_mesh2D[0]])
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/hazardlib/geo/surface/multi.py", line 124, in __init__
    self.edge_set = self._get_edge_set(tol)
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/hazardlib/geo/surface/multi.py", line 158, in _get_edge_set
    raise ValueError("Surface %s not recognised" % str(surface))
ValueError: Surface <openquake.hazardlib.tests.geo.surface.multi_test._BaseMultiTestCase.FakeSurface object at 0x7f0127a05eb8> not recognised

======================================================================
ERROR: test_top_edge_depth (openquake.hazardlib.tests.geo.surface.multi_test.SurfacePropertiesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/hazardlib/tests/geo/surface/multi_test.py", line 198, in test_top_edge_depth
    surf = MultiSurface(self.surfaces_mesh2D)
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/hazardlib/geo/surface/multi.py", line 124, in __init__
    self.edge_set = self._get_edge_set(tol)
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/hazardlib/geo/surface/multi.py", line 158, in _get_edge_set
    raise ValueError("Surface %s not recognised" % str(surface))
ValueError: Surface <openquake.hazardlib.tests.geo.surface.multi_test._BaseMultiTestCase.FakeSurface object at 0x7f0127a05198> not recognised

======================================================================
FAIL: test_point_outside (openquake.hazardlib.tests.geo.surface.base_surface_test.GetJoynerBooreDistanceTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/hazardlib/tests/geo/surface/base_surface_test.py", line 117, in test_point_outside
    self.assertTrue(numpy.allclose(dists, expected_dists, atol=0.2))
AssertionError: False is not true

======================================================================
FAIL: test_2 (openquake.hazardlib.tests.geo.surface.base_surface_test.GetMinDistanceTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/hazardlib/tests/geo/surface/base_surface_test.py", line 59, in test_2
    places=4)
AssertionError: 40.1213468 != 40.09707543926494 within 4 places

======================================================================
FAIL: test_4 (openquake.hazardlib.tests.geo.surface.base_surface_test.GetMinDistanceTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/hazardlib/tests/geo/surface/base_surface_test.py", line 72, in test_4
    places=4)
AssertionError: 55.6159556 != 55.58568426746575 within 4 places

======================================================================
FAIL: test_several_sites (openquake.hazardlib.tests.geo.surface.base_surface_test.GetMinDistanceTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/hazardlib/tests/geo/surface/base_surface_test.py", line 79, in test_several_sites
    self.assertTrue(numpy.allclose(dists, expected_dists))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 170 tests in 0.436s

FAILED (errors=17, failures=4)
```

I'm not able to solve all of them, so I'll let @mmpagani or @micheles fixing them

**Comment by daniviga** [comment]
> *It is important to note that the default behavior of nose is to not include tests from files which are executable.* To include tests from such files, remove their executable bit or use the –exe flag (see ‘Options’ section below).

 http://nose.readthedocs.io/en/latest/usage.html

**Comment by daniviga** [comment]
Superseded by #3897
