### ISSUE TITLE
Error when exporting data: oq1 export -d ./ avg_losses-stats

### ISSUE THREAD

**Issue by CatalinaYepes** [gem/oq-engine#3942]
The following error occurs when trying `oq1 export -d ./ avg_losses-stats`:

`Traceback (most recent call last):
  File "/opt/openquake/oq-engine/openquake/baselib/datastore.py", line 383, in _getitem_
    val = self.hdf5[key]
  File "/opt/openquake/oq-engine/openquake/baselib/hdf5.py", line 333, in _getitem_
    h5obj = super().__getitem__(path)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/opt/openquake/lib/python3.6/site-packages/h5py/_hl/group.py", line 177, in _getitem_
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'avg_losses-rlzs' doesn't exist)"`

The same output can be exported as `oq1 engine --eo OUTPUT_ID` without having errors.

**Comment by micheles** [comment]
Cata, which is the calculation ID which has this problem? I cannot reproduce it with the demo.
