### ISSUE TITLE
Cannot specify openquake.cfg using oq engine --config-file

### ISSUE THREAD

**Issue by nackerley** [gem/oq-engine#4077]
The --config-file switch to oq engine currently fails:
```bash
$ oq engine --config-file ~/src/oq-engine/openquake/engine/openquake.cfg --run ~/src/oq-engine/demos/hazard/AreaSourceClassicalPSHA/job.ini 
Traceback (most recent call last):
  File "/opt/openquake/lib/python3.6/site-packages/openquake/baselib/__init__.py", line 36, in __getattr__
    return self[key]
KeyError: 'load'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/bin/oq", line 11, in <module>
    load_entry_point('openquake.engine==3.2.0.post1', 'console_scripts', 'oq')()
  File "/opt/openquake/lib/python3.6/site-packages/openquake/commands/__main__.py", line 51, in oq
    parser.callfunc()
  File "/opt/openquake/lib/python3.6/site-packages/openquake/baselib/sap.py", line 183, in callfunc
    return self.func(**vars(namespace))
  File "/opt/openquake/lib/python3.6/site-packages/openquake/baselib/sap.py", line 242, in main
    return func(**kw)
  File "/opt/openquake/lib/python3.6/site-packages/openquake/commands/engine.py", line 124, in engine
    config.load(os.path.abspath(os.path.expanduser(config_file)))
  File "/opt/openquake/lib/python3.6/site-packages/openquake/baselib/__init__.py", line 38, in __getattr__
    raise AttributeError(key)
AttributeError: load
```
I thnk it's because the call to be load() should be a call to read() at this line:
https://github.com/gem/oq-engine/blob/1dae33fb815f45424ca2c102dd5819800a4cb65a/openquake/commands/engine.py#L123

Should I go ahead and put together a pull request, or am I missing something?

**Comment by micheles** [comment]
We rename load->read and we did not have a test checking that functionality, since we use very rarely. The fix is trivial.
