### ISSUE TITLE
'Continue' feature does not work with shakemap calculations

### ISSUE THREAD

**Issue by daniviga** [gem/oq-engine#4392]
```python
2019-01-28T11:03:52.44,INFO,MainProcess/10777,daniele running /tmp/tmph_y2j493/Scenario_Damage_and_Risk/job.ini [--hc=1]
2019-01-28T11:03:52.45,INFO,MainProcess/10777,Using engine version 3.4.0-git005d73b944
2019-01-28T11:03:54.53,WARNING,MainProcess/10777,There is no rupture_model, the calculator will just import data without performing any calculation
2019-01-28T11:03:54.54,CRITICAL,MainProcess/10777,
2019-01-28T11:03:54.55,CRITICAL,MainProcess/10777,Traceback (most recent call last):
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/engine/engine.py", line 310, in run_calc
    close=False, **kw)
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/calculators/base.py", line 277, in run
    self.pre_execute()
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/calculators/scenario.py", line 46, in pre_execute
    super().pre_execute()
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/calculators/base.py", line 520, in pre_execute
    parent['oqparam'].calculation_mode)
  File "/home/daniele/GIT/gem/openquake/oq-engine/openquake/calculators/base.py", line 134, in check_precalc_consistency
    ok_mode = PRECALC_MAP[calc_mode]
KeyError: 'scenario'
```

Trying to run a 'shakemap' job an error is raised when trying to use the 'continue' feature to run the actual calculation (scenario in this case) on top of a 'preparation' calculation (`id=1` in the example).

Error is reproducible with Petros examples.

/cc @pslh

**Comment by daniviga** [comment]
We should document better the behavior of `job_*.ini` and the WebUI
