### ISSUE TITLE
Cannot export calculations older than 2019-02-24

### ISSUE THREAD

**Issue by rcgee** [gem/oq-engine#4504]
I am able export a calculation completed 2019-02-28, for example:
`oq1 engine --eos 22525 . `

I am not able to export calculations from earlier than 2019-02-24, for example:
`oq1 engine --eos 22516 .`
`oq1 engine --eos 22349 .`

This is the error: https://oq1.wilson.openquake.org/v1/calc/22516/result/27493?export_type=csv

Full traceback is:

```
During handling of the above exception, another exception occurred:
    yield k, hdf5.extract(dstore['hmaps-stats'], ALL, i, s, ALL)[:, 0]
  File "/opt/openquake/oq-engine/openquake/baselib/datastore.py", line 402, in __getitem__

During handling of the above exception, another exception occurred:
  File "/opt/openquake/oq-engine/openquake/commands/engine.py", line 272, in engine
    hc_id, os.path.expanduser(target_dir), exports or 'csv,xml'):
  File "/opt/openquake/oq-engine/openquake/engine/export/core.py", line 102, in export_outputs
    dskey, job_id, datadir, target_dir, export_types):
    exported = export(output_key, dstore)
  File "/opt/openquake/oq-engine/openquake/baselib/general.py", line 554, in __call__
    yield k, hdf5.extract(dstore['hmaps-stats'], ALL, i, s, ALL)[:, 0]
  File "/opt/openquake/oq-engine/openquake/baselib/datastore.py", line 402, in __getitem__
There is no exporter for fullreport, csv,xml
Exporting hcurves...
Traceback (most recent call last):

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/openquake/oq-engine/openquake/engine/export/core.py", line 65, in export_from_db
    exported = export(output_key, dstore)
  File "/opt/openquake/oq-engine/openquake/baselib/general.py", line 554, in __call__
    return self[key](obj, *args, **kw)
  File "/opt/openquake/oq-engine/openquake/calculators/export/hazard.py", line 381, in export_hcurves_csv
    hmap = dict(extract(dstore, 'hmaps?kind=' + kind))[kind]
  File "/opt/openquake/oq-engine/openquake/calculators/extract.py", line 356, in extract_hmaps
    yield k, hdf5.extract(dstore['hmaps-stats'], ALL, i, s, ALL)[:, 0]
  File "/opt/openquake/oq-engine/openquake/baselib/datastore.py", line 402, in __getitem__
    raise KeyError('No %r found in %s' % (key, self))
KeyError: "No 'hmaps-stats' found in <DataStore /home/oqdata_shared/rgee/oqdata/calc_22516.hdf5 open>"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/oq1", line 11, in <module>
    load_entry_point('openquake.engine', 'console_scripts', 'oq')()
  File "/opt/openquake/oq-engine/openquake/commands/__main__.py", line 50, in oq
    parser.callfunc()
  File "/opt/openquake/oq-engine/openquake/baselib/sap.py", line 182, in callfunc
    return self.func(**vars(namespace))
  File "/opt/openquake/oq-engine/openquake/baselib/sap.py", line 241, in main
    return func(**kw)
  File "/opt/openquake/oq-engine/openquake/commands/engine.py", line 272, in engine
    hc_id, os.path.expanduser(target_dir), exports or 'csv,xml'):
  File "/opt/openquake/oq-engine/openquake/engine/export/core.py", line 102, in export_outputs
    dskey, job_id, datadir, target_dir, export_types):
  File "/opt/openquake/oq-engine/openquake/engine/export/core.py", line 125, in export_output
    yield from export_from_db(outkey, calc_id, datadir, target_dir)
  File "/opt/openquake/oq-engine/openquake/engine/export/core.py", line 72, in export_from_db
    (output_key + (version, tb_str, err)))
openquake.engine.export.core.DataStoreExportError: Could not export hcurves in csv: the datastore is at version 3.4.0-gita03439de2c, but the exporter at version 3.4.0-git0fba8f7b68
  File "/opt/openquake/oq-engine/openquake/engine/export/core.py", line 65, in export_from_db
    exported = export(output_key, dstore)
  File "/opt/openquake/oq-engine/openquake/baselib/general.py", line 554, in __call__
    return self[key](obj, *args, **kw)
  File "/opt/openquake/oq-engine/openquake/calculators/export/hazard.py", line 381, in export_hcurves_csv
    hmap = dict(extract(dstore, 'hmaps?kind=' + kind))[kind]
  File "/opt/openquake/oq-engine/openquake/calculators/extract.py", line 356, in extract_hmaps
    yield k, hdf5.extract(dstore['hmaps-stats'], ALL, i, s, ALL)[:, 0]
  File "/opt/openquake/oq-engine/openquake/baselib/datastore.py", line 402, in __getitem__
    raise KeyError('No %r found in %s' % (key, self))
"No 'hmaps-stats' found in <DataStore /home/oqdata_shared/rgee/oqdata/calc_22516.hdf5 open>"
```

**Comment by micheles** [comment]
It is expected, @rcgee . Please ask Daniele to put the branch that was used to run the calculation, so you can export it, and then restore the master branch. The command to see the git version is
```
$ oq show_attrs / 22516
```

**Comment by micheles** [comment]
BTW, @rcgee , you can run the engine with `oq engine --run job.ini -e csv` and then you will not have this kind of problems.
