### ISSUE TITLE
Connection issues from the WebUI and the QGIS plugin

### ISSUE THREAD

**Issue by ptormene** [gem/oq-engine#4650]
Cata pointed out that on her mac she frequently has connection issues, with error messages like these (from the IRMT plugin and from the WebUI):

```python
ERROR Internal Server Error: /v1/calc/list
Traceback (most recent call last):
  File "/Users/cyepes/py36/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/cyepes/py36/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/cyepes/py36/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, callback_args, *callback_kwargs)
  File "/Users/cyepes/py36/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, args, *kwargs)
  File "/Users/cyepes/openquake/oq-engine/openquake/server/views.py", line 99, in wrap
    response = func(request, args, *kwargs)
  File "/Users/cyepes/openquake/oq-engine/openquake/server/views.py", line 310, in calc_list
    utils.get_acl_on(request), id)
  File "/Users/cyepes/openquake/oq-engine/openquake/commonlib/logs.py", line 53, in dbcmd
    res = sock.send((action,) + args)
  File "/Users/cyepes/openquake/oq-engine/openquake/baselib/zeromq.py", line 147, in send
    self.zsocket.send_pyobj(obj)
  File "/Users/cyepes/py36/lib/python3.6/site-packages/zmq/sugar/socket.py", line 602, in send_pyobj
    return self.send(msg, flags=flags, **kwargs)
  File "/Users/cyepes/py36/lib/python3.6/site-packages/zmq/sugar/socket.py", line 391, in send
    return super(Socket, self).send(data, flags=flags, copy=copy, track=track)
  File "zmq/backend/cython/socket.pyx", line 727, in zmq.backend.cython.socket.Socket.send
  File "zmq/backend/cython/socket.pyx", line 774, in zmq.backend.cython.socket.Socket.send
  File "zmq/backend/cython/socket.pyx", line 249, in zmq.backend.cython.socket._send_copy
  File "zmq/backend/cython/socket.pyx", line 244, in zmq.backend.cython.socket._send_copy
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Operation cannot be accomplished in current state
INFO "GET /v1/calc/list?relevant=true HTTP/1.1" 200 4618
```

```python
INFO "GET /v1/calc/list?relevant=true HTTP/1.1" 200 4618
Resource temporarily unavailable (bundled/zeromq/src/signaler.cpp:301)
```

Something similar happened also to me, perhaps more frequently while using a virtual machine.

The connection usually comes back after a short while. While you use the IRMT plugin, it can be quite annoying, because the plugin closes the dialog that drives the engine when it happens, and it opens the settings to give the user the possibility to change the connection settings. I am changing the behavior of the plugin to be more tolerant when the connection fails, but without hiding the problem.

**Comment by daniviga** [comment]
Could be a regression of https://github.com/gem/oq-engine/pull/4475

**Comment by daniviga** [comment]
Ways to reproduce:

- use a docker image with `--cpus 0.5` or use `systemd-run --user --scope -p CPUQuota=10% oq webui start`
- run several `while true; do curl http://localhost:8800/v1/calc/list?relevant=true ; sleep 0.1; done` (also changing the `sleep` factor)

**Comment by daniviga** [comment]
With #4665 I'm not able to reproduce the issue anymore
