### ISSUE TITLE
Scenario risk csv outputs

### ISSUE THREAD

**Issue by raoanirudh** [gem/oq-engine#4761]
#### Four issues:
- [x] The **realizations** output in the scenario calculators should list the names of the GSIMs used for the calculation, for easier recognition. Instead, the current output follows the format of the realizations output for the probabilistic calculators and lists the branch paths (eg. b_1~b21) rather than the GSIM names.
- [x] The **losses_by_event** output for scenario_risk should either have the realization id, or the engine should export separate files per realization 
- [x] The **agglosses** output for scenario_risk should list the aggregate losses separately for each realization, or the engine should export separate files per realization 

- [x] The **losses_by_asset** exporter is currently broken for some calculations and ends with the following error:
```sh
Traceback (most recent call last):
  File "/usr/local/bin/oq1", line 11, in <module>
    load_entry_point('openquake.engine', 'console_scripts', 'oq')()
  File "/opt/openquake/oq-engine/openquake/commands/__main__.py", line 50, in oq
    parser.callfunc()
  File "/opt/openquake/oq-engine/openquake/baselib/sap.py", line 181, in callfunc
    return self.func(**vars(namespace))
  File "/opt/openquake/oq-engine/openquake/baselib/sap.py", line 251, in main
    return func(**kw)
  File "/opt/openquake/oq-engine/openquake/commands/engine.py", line 240, in engine
    exports or 'csv,xml'):
  File "/opt/openquake/oq-engine/openquake/engine/export/core.py", line 125, in export_output
    yield from export_from_db(outkey, calc_id, datadir, target_dir)
  File "/opt/openquake/oq-engine/openquake/engine/export/core.py", line 72, in export_from_db
    (output_key + (version, tb_str, err)))
openquake.engine.export.core.DataStoreExportError: Could not export losses_by_asset in csv
  File "/opt/openquake/oq-engine/openquake/engine/export/core.py", line 65, in export_from_db
    exported = export(output_key, dstore)
  File "/opt/openquake/oq-engine/openquake/baselib/general.py", line 554, in __call__
    return self[key](obj, *args, **kw)
  File "/opt/openquake/oq-engine/openquake/calculators/export/risk.py", line 211, in export_losses_by_asset
    assets = get_assets(dstore)
  File "/opt/openquake/oq-engine/openquake/commonlib/util.py", line 173, in get_assets
    tup = tuple(b'"%s"' % tag[t][a[t]].encode('utf-8') for t in tagnames)
  File "/opt/openquake/oq-engine/openquake/commonlib/util.py", line 173, in <genexpr>
    tup = tuple(b'"%s"' % tag[t][a[t]].encode('utf-8') for t in tagnames)
index 65165 is out of bounds for axis 0 with size 7

**Comment by micheles** [comment]
[job.zip](https://github.com/gem/oq-engine/files/3243388/job.zip)
