### ISSUE TITLE
iml_disagg doesn't work if multiple IMLs are given

### ISSUE THREAD

**Issue by rcgee** [gem/oq-engine#4787]
This issue was discovered by Youngkyu Cho, who is interested in running disaggregation for multiple imls. 

I confirm his error by running [qa_tests_data/disagg/case_2](https://github.com/gem/oq-engine/blob/master/openquake/qa_tests_data/disagg/case_2/job.ini#L39). The calculations works fine when I use:

`iml_disagg = {'SA(0.10)': 0.1}`

But gives an error (below) when I use:

`iml_disagg = {'SA(0.10)': [0.1, 0.2]}`

```
  File "/home/rgee/openquake/git/oq-engine/openquake/calculators/base.py", line 197, in run
    self.result = self.execute()
  File "/home/rgee/openquake/git/oq-engine/openquake/calculators/disaggregation.py", line 162, in execute
    return self.full_disaggregation(curves)
  File "/home/rgee/openquake/git/oq-engine/openquake/calculators/disaggregation.py", line 264, in full_disaggregation
    R, oq.iml_disagg, oq.imtls, oq.poes_disagg or (None,), curves))
  File "/home/rgee/openquake/git/oq-engine/openquake/calculators/disaggregation.py", line 62, in gen_iml3s
    arr[:, m, 0] = imtls[imt]
ValueError: could not broadcast input array from shape (2) into shape (4)
[2019-06-09 11:16:54,801 #18569 CRITICAL] Traceback (most recent call last):
  File "/home/rgee/openquake/git/oq-engine/openquake/engine/engine.py", line 339, in run_calc
    close=False, **kw)
  File "/home/rgee/openquake/git/oq-engine/openquake/calculators/base.py", line 197, in run
    self.result = self.execute()
  File "/home/rgee/openquake/git/oq-engine/openquake/calculators/disaggregation.py", line 162, in execute
    return self.full_disaggregation(curves)
  File "/home/rgee/openquake/git/oq-engine/openquake/calculators/disaggregation.py", line 264, in full_disaggregation
    R, oq.iml_disagg, oq.imtls, oq.poes_disagg or (None,), curves))
  File "/home/rgee/openquake/git/oq-engine/openquake/calculators/disaggregation.py", line 62, in gen_iml3s
    arr[:, m, 0] = imtls[imt]
ValueError: could not broadcast input array from shape (2) into shape (4)

Traceback (most recent call last):
  File "/home/rgee/openquake/oqenv/bin/oq", line 11, in <module>
    load_entry_point('openquake.engine', 'console_scripts', 'oq')()
  File "/home/rgee/openquake/git/oq-engine/openquake/commands/__main__.py", line 50, in oq
    parser.callfunc()
  File "/home/rgee/openquake/git/oq-engine/openquake/baselib/sap.py", line 181, in callfunc
    return self.func(**vars(namespace))
  File "/home/rgee/openquake/git/oq-engine/openquake/baselib/sap.py", line 251, in main
    return func(**kw)
  File "/home/rgee/openquake/git/oq-engine/openquake/commands/engine.py", line 201, in engine
    exports, reuse_hazard)
  File "/home/rgee/openquake/git/oq-engine/openquake/commands/engine.py", line 115, in smart_run
    hc_id = run_job(job_ini, log_level, log_file, exports)
  File "/home/rgee/openquake/git/oq-engine/openquake/commands/engine.py", line 68, in run_job
    eng.run_calc(job_id, oqparam, exports, **kw)
  File "/home/rgee/openquake/git/oq-engine/openquake/engine/engine.py", line 339, in run_calc
    close=False, **kw)
  File "/home/rgee/openquake/git/oq-engine/openquake/calculators/base.py", line 197, in run
    self.result = self.execute()
  File "/home/rgee/openquake/git/oq-engine/openquake/calculators/disaggregation.py", line 162, in execute
    return self.full_disaggregation(curves)
  File "/home/rgee/openquake/git/oq-engine/openquake/calculators/disaggregation.py", line 264, in full_disaggregation
    R, oq.iml_disagg, oq.imtls, oq.poes_disagg or (None,), curves))
  File "/home/rgee/openquake/git/oq-engine/openquake/calculators/disaggregation.py", line 62, in gen_iml3s
    arr[:, m, 0] = imtls[imt]
ValueError: could not broadcast input array from shape (2) into shape (4)
```

**Comment by micheles** [comment]
This is not an error, @rcgee , iml_disagg does not accept multiple IMLs and never did. It is just a matter of documenting it properly.

**Comment by MohsenKohrangi** [comment]
Hello Micheles,

I am facing the same problem. There is not any other way to do the disaggregation for multiple IM levels in one run? 

If this is not doable, then the only way I can think of is running the hazard once and find the PoE of the corresponding IM values I need and then run the disaggregation using the obtained PoEs.
This is correct?

Thanks
Mohsen
