### ISSUE TITLE
test failed due to permission error

### ISSUE THREAD

**Issue by dynaryu** [gem/oq-engine#4941]
python -m unittest openquake.calculators.tests.classical_damage_test.ClassicalDamageTestCase failed as below:
```
======================================================================
ERROR: test_case_1a (openquake.calculators.tests.classical_damage_test.ClassicalDamageTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/apps/openquake/3.6/src/oq-engine/openquake/calculators/tests/classical_damage_test.py", line 100, in test_case_1a
    self.check(case_1a)
  File "/apps/openquake/3.6/src/oq-engine/openquake/calculators/tests/classical_damage_test.py", line 88, in check
    self.run_calc(case.__file__, 'job_haz.ini')
  File "/apps/openquake/3.6/src/oq-engine/openquake/calculators/tests/__init__.py", line 113, in run_calc
    self.calc = self.get_calc(testfile, inis[0], **kw)
  File "/apps/openquake/3.6/src/oq-engine/openquake/calculators/tests/__init__.py", line 103, in get_calc
    oq.validate()
  File "/apps/openquake/3.6/src/oq-engine/openquake/hazardlib/valid.py", line 1237, in validate
    raise ValueError(doc)
ValueError:
export_dir=/apps/openquake/3.6/src/oq-engine/openquake/qa_tests_data/classical_damage/case_1a must refer to a directory,
and the user must have the permission to write on it.

```

**Comment by micheles** [comment]
It looks like you are not using a development installation with a virtualenv. Again, this is an installation problem. GitHub should be used for bugs.
