### ISSUE TITLE
Allow hostnames to be used when on zmq

### ISSUE THREAD

**Issue by daniviga** [gem/oq-engine#5005]
Like 

```
host_cores = winehouse-bond -1, joplin-bond -1, makeba-bond -1, holiday-bond -1
```

it actually does not work

```
2019-08-21T15:29:26.13,CRITICAL,MainProcess/22380,Traceback (most recent call last):
  File "/opt/openquake3/oq-engine/openquake/engine/engine.py", line 335, in run_calc
    logging.info('WorkerPool %s',  master.wait_pools(seconds=30))
  File "/opt/openquake3/oq-engine/openquake/baselib/workerpool.py", line 77, in wait_pools
    raise TimeoutError(status)
openquake.baselib.workerpool.TimeoutError: [('winehouse-bond', 'not-running'), ('joplin-bond', 'not-running'), ('makeba-bond', 'not-running'), ('holiday-bond', 'not-running')]
```

**Comment by micheles** [comment]
This is not needed anymore.
