### ISSUE TITLE
Bug when extracting ruptures from EB calulations

### ISSUE THREAD

**Issue by CatalinaYepes** [gem/oq-engine#5485]
OQ 3.8 Windows users get the following error when trying to extract the rupture information:

```C:\Program Files\OpenQuake Engine>oq extract rupture/72803 483
c:\program files\openquake engine\python3.6\lib\site-packages\openquake\hazardlib\gsim\base.py:334: DeprecationWarning: MontalvaEtAl2016SSlab is deprecated - use MontalvaEtAl2017SSlab instead
  warnings.warn(msg, DeprecationWarning)
c:\program files\openquake engine\python3.6\lib\site-packages\openquake\hazardlib\gsim\base.py:334: DeprecationWarning: MontalvaEtAl2016SInter is deprecated - use MontalvaEtAl2017SInter instead
  warnings.warn(msg, DeprecationWarning)
INFO:root:There are 0/1 heavy tasks
Traceback (most recent call last):
  File "c:\program files\openquake engine\python3.6\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\openquake engine\python3.6\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\OpenQuake Engine\python3.6\Scripts\oq.exe\__main__.py", line 7, in <module>
  File "c:\program files\openquake engine\python3.6\lib\site-packages\openquake\commands\__main__.py", line 54, in oq
    parser.callfunc()
  File "c:\program files\openquake engine\python3.6\lib\site-packages\openquake\baselib\sap.py", line 181, in callfunc
    return self.func(**vars(namespace))
  File "c:\program files\openquake engine\python3.6\lib\site-packages\openquake\baselib\sap.py", line 251, in main
    return func(**kw)
  File "c:\program files\openquake engine\python3.6\lib\site-packages\openquake\commands\extract.py", line 39, in extract
    open(fname, 'w').write(obj.toml())
PermissionError: [Errno 13] Permission denied: 'rupture-72803_483.txt'
```

**Comment by micheles** [comment]
There is no bug: Ana lucks writing permission on the current directory.
