### ISSUE TITLE
Error while using `to_shapefile` with the JPN model

### ISSUE THREAD

**Issue by mmpagani** [gem/oq-engine#5744]
While running `oq to_shapefile ssm01.xml` I get the following:

Extracting ssm01_ files
Traceback (most recent call last):
  File "/Users/mpagani/Repos/vire/bin/oq", line 11, in <module>
    load_entry_point('openquake.engine', 'console_scripts', 'oq')()
  File "/Users/mpagani/Repos/vire/src/oq-engine/openquake/commands/__main__.py", line 54, in oq
    parser.callfunc()
  File "/Users/mpagani/Repos/vire/src/oq-engine/openquake/baselib/sap.py", line 181, in callfunc
    return self.func(**vars(namespace))
  File "/Users/mpagani/Repos/vire/src/oq-engine/openquake/baselib/sap.py", line 251, in main
    return func(**kw)
  File "/Users/mpagani/Repos/vire/src/oq-engine/openquake/commands/to_shapefile.py", line 40, in to_shapefile
    shapefileparser.ShapefileParser().write(output, source_model)
  File "/Users/mpagani/Repos/vire/src/oq-engine/openquake/commonlib/shapefileparser.py", line 1071, in write
    set_params(w_planar, src)
  File "/Users/mpagani/Repos/vire/src/oq-engine/openquake/commonlib/shapefileparser.py", line 454, in set_params
    params.update(extract_geometry_params(src))
  File "/Users/mpagani/Repos/vire/src/oq-engine/openquake/commonlib/shapefileparser.py", line 289, in extract_geometry_params
    surf_attrs = parse_planar_fault_geometry(surface)
  File "/Users/mpagani/Repos/vire/src/oq-engine/openquake/commonlib/shapefileparser.py", line 230, in parse_planar_fault_geometry
    geometry = {"strike": node.attrib["strike"],
KeyError: 'strike'

**Comment by micheles** [comment]
I really want to abandon the shapefile format. Or alternatively, leave everything to @ptormene ;-)
The final purpose is just plotting of the sources, right?

**Comment by ptormene** [comment]
In general, I agree we should move from shapefiles to something that has less restrictions and issues (e.g. geopackages), unless we have good reasons to keep using shapefiles.

**Comment by julgp** [comment]
We can abandon the shapefile format for something better and open. My only concern is to maintain the possibility to plotting, modify (geometry and parameters) in a GIS environment the sources, and convert (from the selected format) the sources to .xml format.

**Comment by micheles** [comment]
See also https://github.com/gem/oq-engine/issues/5781

**Comment by matt-schmid** [comment]
@mmpagani: FYI the problem in this case for me was that planarSurface is missing the strike and dip information in the input NRML. Once added, the oq to_shapefile export works for me.

**Comment by mmpagani** [comment]
@matt-schmid thank you very much for the feedback. We will make sure that this information is either included in the nrml (although it might not be possible for all the non-parametric sources) or computed during the exporting phase (preferable).

**Comment by micheles** [comment]
Now the Japan model can be converted into .csv or .gpkg files, so this ticket can be closed.
