### ISSUE TITLE
Problem with `nrml_to`

### ISSUE THREAD

**Issue by mmpagani** [gem/oq-engine#6327]
Running this command (on a Mac) generates an error:
```
oq nrml_to gpkg ssm/EMCA_seismozonesv1.0.xml ./../gis
```
presumably there is something wrong in the way we handle the `outdir` option

**Comment by micheles** [comment]
Please post the traceback and gives me the XML file.

**Comment by mmpagani** [comment]
```
INFO:root:Reading ssm/EMCA_seismozonesv1.0.xml
INFO:root:Saving 21 sources on layer A3
INFO:root:Reading ./../gis
Traceback (most recent call last):
  File "/Users/mpagani/Repos/venv/bin/oq", line 11, in <module>
    load_entry_point('openquake.engine==3.10.0', 'console_scripts', 'oq')()
  File "/Users/mpagani/Repos/venv/src/oq-engine/openquake/commands/__main__.py", line 54, in oq
    parser.callfunc()
  File "/Users/mpagani/Repos/venv/src/oq-engine/openquake/baselib/sap.py", line 181, in callfunc
    return self.func(**vars(namespace))
  File "/Users/mpagani/Repos/venv/src/oq-engine/openquake/baselib/sap.py", line 251, in main
    return func(**kw)
  File "/Users/mpagani/Repos/venv/src/oq-engine/openquake/commands/nrml_to.py", line 135, in nrml_to
    root = nrml.read(fname)
  File "/Users/mpagani/Repos/venv/src/oq-engine/openquake/hazardlib/nrml.py", line 348, in read
    nrml = vparser.parse_file(source)
  File "/Users/mpagani/Repos/venv/src/oq-engine/openquake/baselib/node.py", line 870, in parse_file
    with open(file_or_fname, 'rb') as f:
IsADirectoryError: [Errno 21] Is a directory: './../gis'
```

**Comment by mmpagani** [comment]
You get it with every model
