### ISSUE TITLE
Getting an Error in demo file of Area Source Classical PSHA

### ISSUE THREAD

**Issue by auliakhalqillah** [gem/oq-engine#7369]
I got an error when compiling the demo file of Area Source Classical PSHA, where the error is

```
INFO:root:Creating the initial schema from 0000-base_schema.sql
INFO:root:Creating the versioning table revision_info
INFO:root:Executing /home/aulia/openquake/lib/python3.8/site-packages/openquake/server/db/schema/upgrades/0001-job.py
INFO:root:Executing /home/aulia/openquake/lib/python3.8/site-packages/openquake/server/db/schema/upgrades/0002-job.py
INFO:root:Executing /home/aulia/openquake/lib/python3.8/site-packages/openquake/server/db/schema/upgrades/0003-output.sql
INFO:root:Executing /home/aulia/openquake/lib/python3.8/site-packages/openquake/server/db/schema/upgrades/0004-job.py
INFO:root:Executing /home/aulia/openquake/lib/python3.8/site-packages/openquake/server/db/schema/upgrades/0005-index.sql
INFO:root:Executing /home/aulia/openquake/lib/python3.8/site-packages/openquake/server/db/schema/upgrades/0006-checksum.sql
INFO:root:Upgrade completed in 0.03844928741455078 seconds
WARNING:root:DB server started with /home/aulia/openquake/bin/python3 on tcp://127.0.0.1:1908, pid 657
[2021-11-15 14:39:24 #1 INFO] aulia running /home/aulia/openquake/demos/hazard/AreaSourceClassicalPSHA/job.ini [--hc=None]
[2021-11-15 14:39:24 #1 INFO] Using engine version 3.12.1
[2021-11-15 14:39:25 #1 WARNING] Using 16 cores on ASUS-FX506LU
[2021-11-15 14:39:25 #1 INFO] Validated source_model_logic_tree.xml in 0.00 seconds
[2021-11-15 14:39:25 #1 INFO] Checksum of the input files: 744842871
[2021-11-15 14:39:25 #1 INFO] Reading the risk model if present
[2021-11-15 14:39:25 #1 INFO] Inferring the hazard grid
[2021-11-15 14:39:25 #1 INFO] Read N=624 hazard sites and L=360 hazard levels
[2021-11-15 14:39:25 #1 INFO] There are 1 not vectorized GMPEs
[2021-11-15 14:39:26 #1 INFO] Total number of logic tree paths = 1
[2021-11-15 14:39:26 #1 INFO] Reading the source model(s) in parallel
[2021-11-15 14:39:26 #1 INFO] read_source_model 100% [1 submitted, 0 queued]
[2021-11-15 14:39:26 #1 INFO] Received {'/home/aulia/openquake/demos/hazard/AreaSourceClassicalPSHA/source_model.xml': '1.71 KB'} in 0 seconds from read_source_model
[2021-11-15 14:39:26 #1 INFO] There are 1 groups and 1 sources with len(trt_smrs)=1.00
[2021-11-15 14:39:26 #1 INFO] Checking the sources bounding box
[2021-11-15 14:39:26 #1 INFO] max_dist Active Shallow Crust: 5.10->200, ... 6.30->200, 6.50->200
[2021-11-15 14:39:27 #1 INFO] Requiring 1.71 MB for full ProbabilityMap of shape (1, 624, 360)
[2021-11-15 14:39:27 #1 INFO] Requiring 1.71 MB for max ProbabilityMap of shape (1, 624, 360)
[2021-11-15 14:39:27 #1 CRITICAL]
Traceback (most recent call last):
  File "/home/aulia/openquake/lib/python3.8/site-packages/h5py/_hl/files.py", line 185, in make_fid
    fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (unable to lock file, errno = 11, error message = 'Resource temporarily unavailable')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aulia/openquake/lib/python3.8/site-packages/openquake/commonlib/datastore.py", line 194, in open
    self.hdf5 = hdf5.File(self.filename, mode)
  File "/home/aulia/openquake/lib/python3.8/site-packages/openquake/baselib/hdf5.py", line 297, in __init__
    super().__init__(name, mode, driver, libver,
  File "/home/aulia/openquake/lib/python3.8/site-packages/h5py/_hl/files.py", line 406, in __init__
    fid = make_fid(name, mode, userblock_size,
  File "/home/aulia/openquake/lib/python3.8/site-packages/h5py/_hl/files.py", line 187, in make_fid
    fid = h5f.create(name, h5f.ACC_EXCL, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 108, in h5py.h5f.create
OSError: Unable to create file (unable to open file: name = '/home/aulia/oqdata/calc_1.hdf5', errno = 17, error message = 'File exists', flags = 15, o_flags = c2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aulia/openquake/lib/python3.8/site-packages/openquake/calculators/base.py", line 233, in run
    self.pre_execute()
  File "/home/aulia/openquake/lib/python3.8/site-packages/openquake/calculators/base.py", line 588, in pre_execute
    self.read_inputs()
  File "/home/aulia/openquake/lib/python3.8/site-packages/openquake/calculators/base.py", line 477, in read_inputs
    self.init()  # do this at the end of pre-execute
  File "/home/aulia/openquake/lib/python3.8/site-packages/openquake/calculators/classical.py", line 460, in init
    self.datastore.swmr_on()
  File "/home/aulia/openquake/lib/python3.8/site-packages/openquake/commonlib/datastore.py", line 233, in swmr_on
    self.open('a')
  File "/home/aulia/openquake/lib/python3.8/site-packages/openquake/commonlib/datastore.py", line 196, in open
    raise OSError('%s in %s' % (exc, self.filename))
OSError: Unable to create file (unable to open file: name = '/home/aulia/oqdata/calc_1.hdf5', errno = 17, error message = 'File exists', flags = 15, o_flags = c2) in /home/aulia/oqdata/calc_1.hdf5
[2021-11-15 14:39:28 #1 CRITICAL] Traceback (most recent call last):
  File "/home/aulia/openquake/lib/python3.8/site-packages/h5py/_hl/files.py", line 185, in make_fid
    fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (unable to lock file, errno = 11, error message = 'Resource temporarily unavailable')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aulia/openquake/lib/python3.8/site-packages/openquake/commonlib/datastore.py", line 194, in open
    self.hdf5 = hdf5.File(self.filename, mode)
  File "/home/aulia/openquake/lib/python3.8/site-packages/openquake/baselib/hdf5.py", line 297, in __init__
    super().__init__(name, mode, driver, libver,
  File "/home/aulia/openquake/lib/python3.8/site-packages/h5py/_hl/files.py", line 406, in __init__
    fid = make_fid(name, mode, userblock_size,
  File "/home/aulia/openquake/lib/python3.8/site-packages/h5py/_hl/files.py", line 187, in make_fid
    fid = h5f.create(name, h5f.ACC_EXCL, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 108, in h5py.h5f.create
OSError: Unable to create file (unable to open file: name = '/home/aulia/oqdata/calc_1.hdf5', errno = 17, error message = 'File exists', flags = 15, o_flags = c2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aulia/openquake/lib/python3.8/site-packages/openquake/calculators/base.py", line 233, in run
    self.pre_execute()
  File "/home/aulia/openquake/lib/python3.8/site-packages/openquake/calculators/base.py", line 588, in pre_execute
    self.read_inputs()
  File "/home/aulia/openquake/lib/python3.8/site-packages/openquake/calculators/base.py", line 477, in read_inputs
    self.init()  # do this at the end of pre-execute
  File "/home/aulia/openquake/lib/python3.8/site-packages/openquake/calculators/classical.py", line 460, in init
    self.datastore.swmr_on()
  File "/home/aulia/openquake/lib/python3.8/site-packages/openquake/commonlib/datastore.py", line 233, in swmr_on
    self.open('a')
  File "/home/aulia/openquake/lib/python3.8/site-packages/openquake/commonlib/datastore.py", line 196, in open
    raise OSError('%s in %s' % (exc, self.filename))
OSError: Unable to create file (unable to open file: name = '/home/aulia/oqdata/calc_1.hdf5', errno = 17, error message = 'File exists', flags = 15, o_flags = c2) in /home/aulia/oqdata/calc_1.hdf5

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aulia/openquake/lib/python3.8/site-packages/openquake/engine/engine.py", line 257, in run_calc
    calc.run()
  File "/home/aulia/openquake/lib/python3.8/site-packages/openquake/calculators/base.py", line 264, in run
    os.remove(self.datastore.tempname)
  File "/home/aulia/openquake/lib/python3.8/site-packages/openquake/baselib/performance.py", line 215, in __exit__
    self.flush(self.h5)
  File "/home/aulia/openquake/lib/python3.8/site-packages/openquake/baselib/performance.py", line 254, in flush
    hdf5.extend(h5['performance_data'], data)
  File "/home/aulia/openquake/lib/python3.8/site-packages/openquake/commonlib/datastore.py", line 467, in __getitem__
    raise ValueError('Cannot find %s in %s' % (key, self))
ValueError: Cannot find performance_data in <DataStore /home/aulia/oqdata/calc_1.hdf5 closed>

Stopping the workers
Traceback (most recent call last):
  File "/home/aulia/openquake/lib/python3.8/site-packages/h5py/_hl/files.py", line 185, in make_fid
    fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (unable to lock file, errno = 11, error message = 'Resource temporarily unavailable')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aulia/openquake/lib/python3.8/site-packages/openquake/commonlib/datastore.py", line 194, in open
    self.hdf5 = hdf5.File(self.filename, mode)
  File "/home/aulia/openquake/lib/python3.8/site-packages/openquake/baselib/hdf5.py", line 297, in __init__
    super().__init__(name, mode, driver, libver,
  File "/home/aulia/openquake/lib/python3.8/site-packages/h5py/_hl/files.py", line 406, in __init__
    fid = make_fid(name, mode, userblock_size,
  File "/home/aulia/openquake/lib/python3.8/site-packages/h5py/_hl/files.py", line 187, in make_fid
    fid = h5f.create(name, h5f.ACC_EXCL, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 108, in h5py.h5f.create
OSError: Unable to create file (unable to open file: name = '/home/aulia/oqdata/calc_1.hdf5', errno = 17, error message = 'File exists', flags = 15, o_flags = c2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aulia/openquake/lib/python3.8/site-packages/openquake/calculators/base.py", line 233, in run
    self.pre_execute()
  File "/home/aulia/openquake/lib/python3.8/site-packages/openquake/calculators/base.py", line 588, in pre_execute
    self.read_inputs()
  File "/home/aulia/openquake/lib/python3.8/site-packages/openquake/calculators/base.py", line 477, in read_inputs
    self.init()  # do this at the end of pre-execute
  File "/home/aulia/openquake/lib/python3.8/site-packages/openquake/calculators/classical.py", line 460, in init
    self.datastore.swmr_on()
  File "/home/aulia/openquake/lib/python3.8/site-packages/openquake/commonlib/datastore.py", line 233, in swmr_on
    self.open('a')
  File "/home/aulia/openquake/lib/python3.8/site-packages/openquake/commonlib/datastore.py", line 196, in open
    raise OSError('%s in %s' % (exc, self.filename))
OSError: Unable to create file (unable to open file: name = '/home/aulia/oqdata/calc_1.hdf5', errno = 17, error message = 'File exists', flags = 15, o_flags = c2) in /home/aulia/oqdata/calc_1.hdf5

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aulia/openquake/bin/oq", line 8, in <module>
    sys.exit(oq())
  File "/home/aulia/openquake/lib/python3.8/site-packages/openquake/commands/__main__.py", line 50, in oq
    sap.run(commands, prog='oq')
  File "/home/aulia/openquake/lib/python3.8/site-packages/openquake/baselib/sap.py", line 225, in run
    return _run(parser(funcdict, **parserkw), argv)
  File "/home/aulia/openquake/lib/python3.8/site-packages/openquake/baselib/sap.py", line 216, in _run
    return func(**dic)
  File "/home/aulia/openquake/lib/python3.8/site-packages/openquake/commands/engine.py", line 169, in main
    run_jobs(jobs)
  File "/home/aulia/openquake/lib/python3.8/site-packages/openquake/engine/engine.py", line 348, in run_jobs
    run_calc(job)
  File "/home/aulia/openquake/lib/python3.8/site-packages/openquake/engine/engine.py", line 257, in run_calc
    calc.run()
  File "/home/aulia/openquake/lib/python3.8/site-packages/openquake/calculators/base.py", line 264, in run
    os.remove(self.datastore.tempname)
  File "/home/aulia/openquake/lib/python3.8/site-packages/openquake/baselib/performance.py", line 215, in __exit__
    self.flush(self.h5)
  File "/home/aulia/openquake/lib/python3.8/site-packages/openquake/baselib/performance.py", line 254, in flush
    hdf5.extend(h5['performance_data'], data)
  File "/home/aulia/openquake/lib/python3.8/site-packages/openquake/commonlib/datastore.py", line 467, in __getitem__
    raise ValueError('Cannot find %s in %s' % (key, self))
ValueError: Cannot find performance_data in <DataStore /home/aulia/oqdata/calc_1.hdf5 closed>
```

does anyone how to solve this problem?

**Comment by micheles** [comment]
You should use the mailing list, not GitHub for this kind of problems. Are you sure that you have permissions to write inside oqdata? You are the first to report such an issue.

**Comment by auliakhalqillah** [comment]
> You should use the mailing list, not GitHub for this kind of problems. Are you sure that you have permissions to write inside oqdata? You are the first to report such an issue.

I'm sorry about that. I was thinking that I can get solutions to this problem in GitHub. I'm sorry, what is that mean **have permissions to write inside oqdata?**

Actually, when I tried to compile the demo file of Scenario Case, it works fine. Then, I tried to compile the demo file of Area Source Classical PSHA, I got these errors.

**Comment by auliakhalqillah** [comment]
For information, I tried to compile the demo file of Area Source Classical PSHA by using OpenQuake 3.11.4 on the Windows platform, and on Ubuntu, I have to use OpenQuake 3.6.0. Both versions work fine. Thank you.
