### ISSUE TITLE
Error using API endpoint v1/calc/run

### ISSUE THREAD

**Issue by schmidni** [gem/oq-engine#7596]
I can use the following code to start a calculation using the API with v3.12.1 and below:

```python
def oqapi_send_pre_calculation(
        job_config: io.StringIO,
        input_model_1: io.StringIO,
        input_model_2: io.StringIO,
        input_model_3: io.StringIO):
    files = locals()   
    response = requests.post(
        'http://localhost:8800/v1/calc/run', files=files)
```

Doing the same with v3.13.0 I get the following error:

```
ERROR:root:Traceback (most recent call last):
  File "/home/schmidni/workspaces/oq-engine/src/oq-engine/openquake/server/views.py", line 546, in calc_run
    job_id = submit_job(request.FILES, ini, user, hazard_job_id)
  File "/home/schmidni/workspaces/oq-engine/src/oq-engine/openquake/server/views.py", line 574, in submit_job
    job_ini = store(request_files, ini, job.calc_id)
  File "/home/schmidni/workspaces/oq-engine/src/oq-engine/openquake/server/views.py", line 141, in store
    for each_file in sorted(request_files.values()):
TypeError: '<' not supported between instances of 'TemporaryUploadedFile' and 'TemporaryUploadedFile'
'<' not supported between instances of 'TemporaryUploadedFile' and 'TemporaryUploadedFile'
```

Removing the `sorted()` on this line https://github.com/gem/oq-engine/blob/bb667bd128e57dab54e9a3a94ce2e9d81823aa3d/openquake/server/views.py#L141 resolves the issue and the job can run.

Am I doing something wrong or is this actually a bug?

**Comment by micheles** [comment]
Looks like a bug. Thanks for reporting it.

**Comment by micheles** [comment]
This is now fixed both in master and in the branch engine-3.13.
