### ISSUE TITLE
Issues with agg_keys

### ISSUE THREAD

**Issue by schmidni** [gem/oq-engine#7918]
Working with aggregated results/risk_by_event/aggregation keys as documented in the advanced manual, I noticed a few issues:

- `oq show agg_id` results in an error:
```
Traceback (most recent call last):
  File "/home/schmidni/workspaces/esloss-core/env/bin/oq", line 8, in <module>
    sys.exit(oq())
  File "/home/schmidni/workspaces/esloss-core/env/lib/python3.8/site-packages/openquake/commands/__main__.py", line 61, in oq
    sap.run(commands, prog='oq')
  File "/home/schmidni/workspaces/esloss-core/env/lib/python3.8/site-packages/openquake/baselib/sap.py", line 225, in run
    return _run(parser(funcdict, **parserkw), argv)
  File "/home/schmidni/workspaces/esloss-core/env/lib/python3.8/site-packages/openquake/baselib/sap.py", line 216, in _run
    return func(**dic)
  File "/home/schmidni/workspaces/esloss-core/env/lib/python3.8/site-packages/openquake/commands/show.py", line 85, in main
    print_(view(what, ds))
  File "/home/schmidni/workspaces/esloss-core/env/lib/python3.8/site-packages/openquake/baselib/general.py", line 564, in __call__
    return self[key](obj, *args, **kw)
  File "/home/schmidni/workspaces/esloss-core/env/lib/python3.8/site-packages/openquake/calculators/views.py", line 1239, in view_agg_id
    dfa = dstore.read_df('agg_keys')
  File "/home/schmidni/workspaces/esloss-core/env/lib/python3.8/site-packages/openquake/commonlib/datastore.py", line 436, in read_df
    return self.hdf5.read_df(key, index, sel, slc)
  File "/home/schmidni/workspaces/esloss-core/env/lib/python3.8/site-packages/openquake/baselib/hdf5.py", line 393, in read_df
    for name in dset.dtype.names:
TypeError: 'NoneType' object is not iterable
```

- similar thing happens when trying to read the datastore:
```
dstore = read(-1)
agg_keys = dstore.read_df("agg_keys")
```

```
Traceback (most recent call last):
  File "/home/schmidni/workspaces/esloss-core/run.py", line 78, in <module>
    agg_keys = dstore.read_df("agg_keys")
  File "/home/schmidni/workspaces/esloss-core/env/lib/python3.8/site-packages/openquake/commonlib/datastore.py", line 436, in read_df
    return self.hdf5.read_df(key, index, sel, slc)
  File "/home/schmidni/workspaces/esloss-core/env/lib/python3.8/site-packages/openquake/baselib/hdf5.py", line 393, in read_df
    for name in dset.dtype.names:
TypeError: 'NoneType' object is not iterable
```

- The last thing I don't know if its a bug or not, but 
`len(dstore['agg_keys']) => 2`
`dstore.read_df('risk_by_event')['agg_id'].max() => 2`
which means that there is one less aggregation keys in the 'agg_keys' datastore than 'agg_id's' in risk_by_event  -> the "total" is not mentioned in the 'agg_keys' part, is that intentional? The answer on [this](https://groups.google.com/g/openquake-users/c/wlieWppKKps/m/1aB3uut7AgAJ) question (joining risk_by_event.agg_id on agg_keys.id) led me to believe that agg_keys and agg_id should be the same length.

Cheers

**Comment by micheles** [comment]
Recently, to implement the multi-aggregation feature requested by Athanasios, the internals were changed and the manual left outdated.

**Comment by schmidni** [comment]
ok, thanks for the upcoming fix. having the agg_id as it is, is obviously fine, just wanted to be sure that its intended this way before I use it that way :)
