### ISSUE TITLE
Calculation failing if there is no loss

### ISSUE THREAD

**Issue by schmidni** [gem/oq-engine#8854]
How to reproduce:
Start a scenario_risk calculation which produces no loss.

Calculation log:
```
2023-06-19T10:11:57.05,INFO,SpawnProcess-43/438836,erm@ermd running /tmp/tmpqze0bmd4/calc_9/job.ini [--hc=None]

2023-06-19T10:11:57.06,INFO,SpawnProcess-43/438836,Using engine version 3.16.0-gita0aa88c026

2023-06-19T10:11:57.13,WARNING,SpawnProcess-43/438836,Using 32 cores on ermd

2023-06-19T10:11:57.61,INFO,SpawnProcess-43/438836,Checksum of the inputs: 192444940 (total size 410.56 MB)

2023-06-19T10:11:57.84,INFO,SpawnProcess-43/438836,Reading /tmp/tmpqze0bmd4/calc_9/exposure.xml

2023-06-19T10:12:12.69,INFO,SpawnProcess-43/438836,Read 40_439 sites and 397_790 assets from the exposure

2023-06-19T10:12:21.19,ERROR,SpawnProcess-43/438836,geohashes are not unique

2023-06-19T10:12:21.27,INFO,SpawnProcess-43/438836,Reducing risk model from 92 to 76 taxonomy strings

2023-06-19T10:12:21.27,INFO,SpawnProcess-43/438836,minimum_asset_loss={'business_interruption': 0, 'contents': 1000, 'nonstructural': 0, 'occupants': 0, 'structural': 2000}

2023-06-19T10:12:23.14,INFO,SpawnProcess-43/438836,Storing 2 aggregation keys

2023-06-19T10:12:48.90,INFO,SpawnProcess-43/438836,Storing 500 events, all relevant

2023-06-19T10:14:03.96,INFO,SpawnProcess-43/438836,Storing risk model

2023-06-19T10:14:04.01,INFO,SpawnProcess-43/438836,There are 0 ruptures and 500 events

2023-06-19T10:14:04.83,INFO,SpawnProcess-43/438836,Preparing tasks

2023-06-19T10:14:16.36,INFO,SpawnProcess-43/438836,ebr_from_gmfs   1% [72 submitted, 0 queued]

...

2023-06-19T10:14:26.58,INFO,SpawnProcess-43/438836,ebr_from_gmfs 100% [72 submitted, 0 queued]

2023-06-19T10:14:26.59,INFO,SpawnProcess-43/438836,Mean time per core=13s, std=1.6s, min=11s, max=16s

2023-06-19T10:14:26.59,INFO,SpawnProcess-43/438836,Received {'alt': '54.98 KB', 'avg': '7.17 KB'} in 17 seconds from ebr_from_gmfs

2023-06-19T10:14:27.66,INFO,SpawnProcess-43/438836,Running PostRiskCalculator with concurrent_tasks = 64

2023-06-19T10:14:27.67,INFO,SpawnProcess-43/438836,Aggregating by [['Canton'], ['CantonGemeinde']]

2023-06-19T10:14:28.45,CRITICAL,SpawnProcess-43/438836,Traceback (most recent call last):
  File "/home/erm/oq-engine/openquake/engine/engine.py", line 279, in run_calc
    calc.run(shutdown=True)
  File "/home/erm/oq-engine/openquake/calculators/base.py", line 243, in run
    self.post_execute(self.result)
  File "/home/erm/oq-engine/openquake/calculators/event_based_risk.py", line 466, in post_execute
    self.build_aggcurves()
  File "/home/erm/oq-engine/openquake/calculators/event_based_risk.py", line 476, in build_aggcurves
    prc.run(exports='')
  File "/home/erm/oq-engine/openquake/calculators/base.py", line 241, in run
    self.result = self.execute()
  File "/home/erm/oq-engine/openquake/calculators/post_risk.py", line 426, in execute
    raise SystemExit('The risk_by_event table is empty!')
SystemExit: The risk_by_event table is empty!
```

The same calculation / outcome for scenario_damage just returns a warning but succeeds, which is what I would expect.
```
2023-06-19T10:50:54.48,WARNING,SpawnProcess-26/439854,There is no damage, perhaps the hazard is too small?

2023-06-19T10:50:55.46,INFO,SpawnProcess-26/439854,Exposing the outputs to the database
```

**Comment by schmidni** [comment]
sorry, should have mentioned that

yes, I use gmfs stored in a csv file:
```
[hazard]
gmfs_csv = gmfs_gen.csv
sites_csv = sites_gen.csv
```
