### ISSUE TITLE
ValueError at /ipt/

### ISSUE THREAD

**Issue by alejocaldeGEM** [gem/oq-engine#8895]
On the engine version 3.16.4, if the user starts the webui and clicks on the `Tools` tab (e.g. to use a feature of the IPT), the following error appears:

`Environment:

Request Method: GET
Request URL: http://localhost:8800/ipt/

Django Version: 3.2.19
Python Version: 3.9.11
Installed Applications:
('openquake.server.db',
 'django.contrib.staticfiles',
 'openquake.server',
 'openquakeplatform',
 'openquakeplatform_ipt',
 'openquakeplatform_taxtweb',
 'openquakeplatform_taxonomy')
Installed Middleware:
('django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware')

Traceback (most recent call last):
  File "C:\Program Files\OpenQuake Engine\python3\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Program Files\OpenQuake Engine\python3\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\OpenQuake Engine\python3\lib\site-packages\openquakeplatform_ipt\views.py", line 633, in view
    exposure_csv_html, exposure_csv_upload = filehtml_create(
  File "C:\Program Files\OpenQuake Engine\python3\lib\site-packages\openquakeplatform_ipt\views.py", line 593, in filehtml_create
    return fh, fh.gem_fileupload()
  File "C:\Program Files\OpenQuake Engine\python3\lib\site-packages\openquakeplatform_ipt\views.py", line 575, in gem_fileupload
    return FileUploadMulti(
  File "C:\Program Files\OpenQuake Engine\python3\lib\site-packages\openquakeplatform_ipt\views.py", line 449, in __init__
    self.fields['file_upload'].widget = forms.ClearableFileInput(
  File "C:\Program Files\OpenQuake Engine\python3\lib\site-packages\django\forms\widgets.py", line 391, in __init__
    raise ValueError(

Exception Type: ValueError at /ipt/
Exception Value: ClearableFileInput doesn't support uploading multiple files.`

![image](https://github.com/gem/oq-engine/assets/43442706/9c5223ee-afd2-478a-a5ae-4226f23222d9)

Engine version 3.16.4
Windows OS
Windows 10 Pro
Chrome Browser

**Comment by micheles** [comment]
Closed because already solved in 3.6.5 with the fix already published.
