### ISSUE TITLE
OpenQuake.Engine==3.17, 3.16 Installation Completed, But Starts with Error Using Python3.10, 3.11

### ISSUE THREAD

**Issue by NimaDolatabadi** [gem/oq-engine#8917]
I have ubuntu 20.04 LTS using Anaconda with custom enviromnet.

the command is simply `pip install openquake.engine==3.17` and `pip install openquake.engine==3.16`

for both version and using python=3.11, 3.10 I'm getting the same error. OpenQuake.Engine==3.15 installs and works fine.
when typing `oq` to get the commands I get the following error instead:

Traceback (most recent call last):
```
  File "/home/nima/src/conda/envs/test/bin/oq", line 8, in <module>
    sys.exit(oq())
             ^^^^
  File "/home/nima/src/conda/envs/test/lib/python3.11/site-packages/openquake/commands/__main__.py", line 48, in oq
    sap.run(commands, prog='oq')
  File "/home/nima/src/conda/envs/test/lib/python3.11/site-packages/openquake/baselib/sap.py", line 212, in run
    return _run(parser(funcdict, **parserkw), argv)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nima/src/conda/envs/test/lib/python3.11/site-packages/openquake/baselib/sap.py", line 182, in parser
    funcdict = pkg2dic(funcdict)
               ^^^^^^^^^^^^^^^^^
  File "/home/nima/src/conda/envs/test/lib/python3.11/site-packages/openquake/baselib/sap.py", line 161, in pkg2dic
    mod = importlib.import_module(dotname[:-3])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nima/src/conda/envs/test/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/nima/src/conda/envs/test/lib/python3.11/site-packages/openquake/commands/run.py", line 25, in <module>
    from pandas.core.common import SettingWithCopyWarning
ImportError: cannot import name 'SettingWithCopyWarning' from 'pandas.core.common' (/home/nima/src/conda/envs/test/lib/python3.11/site-packages/pandas/core/common.py)
```

Reinstalling, creating new env, using older python version, updating anaconda, none of them works at all.

I hope You'd mind giving a hand on this issue.

Regards

Nima

**Comment by micheles** [comment]
We do not support conda at the moment and conda uses a version of pandas which is too new for the engine.
