### ISSUE TITLE
Multiple QA tests fail to run with current master

### ISSUE THREAD

**Issue by raoanirudh** [gem/oq-engine#8986]
- qa_tests_data/scenario/case_21/job.ini
- qa_tests_data/scenario/case_24/job.ini
- qa_tests_data/scenario/case_26/job.ini

currently fail on macOS Big Sur with Python 3.9 with the following traceback (the same tests pass with Python 3.10.8, pytest-7.4.1):

```sh
Traceback (most recent call last):
  File "/usr/bin/oq", line 33, in <module>
    sys.exit(load_entry_point('openquake.engine', 'console_scripts', 'oq')())
  File "/opt/openquake/oq-engine/openquake/commands/__main__.py", line 48, in oq
    sap.run(commands, prog='oq')
  File "/opt/openquake/oq-engine/openquake/baselib/sap.py", line 212, in run
    return _run(parser(funcdict, **parserkw), argv)
  File "/opt/openquake/oq-engine/openquake/baselib/sap.py", line 203, in _run
    return func(**dic)
  File "/opt/openquake/oq-engine/openquake/commands/engine.py", line 175, in main
    run_jobs(jobs)
  File "/opt/openquake/oq-engine/openquake/engine/engine.py", line 408, in run_jobs
    run_calc(jobctx)
  File "/opt/openquake/oq-engine/openquake/engine/engine.py", line 280, in run_calc
    calc.run(shutdown=True)
  File "/opt/openquake/oq-engine/openquake/calculators/base.py", line 253, in run
    raise exc from None
  File "/opt/openquake/oq-engine/openquake/calculators/base.py", line 242, in run
    self.result = self.execute()
  File "/opt/openquake/oq-engine/openquake/calculators/event_based.py", line 604, in execute
    acc = smap.reduce(self.agg_dicts)
  File "/opt/openquake/oq-engine/openquake/baselib/parallel.py", line 887, in reduce
    return self.submit_all().reduce(agg, acc)
  File "/opt/openquake/oq-engine/openquake/baselib/parallel.py", line 630, in reduce
    for result in self:
  File "/opt/openquake/oq-engine/openquake/baselib/parallel.py", line 618, in __iter__
    yield from self._iter()
  File "/opt/openquake/oq-engine/openquake/baselib/parallel.py", line 610, in _iter
    yield result.get()
  File "/opt/openquake/oq-engine/openquake/baselib/parallel.py", line 438, in get
    raise etype(msg)
AssertionError:
  File "/opt/openquake/oq-engine/openquake/baselib/parallel.py", line 461, in new
    val = func(*args)
  File "/opt/openquake/oq-engine/openquake/calculators/event_based.py", line 227, in gen_event_based
    yield event_based(proxies, cmaker, stations, dstore, monitor)
  File "/opt/openquake/oq-engine/openquake/calculators/event_based.py", line 281, in event_based
    gmfdata = strip_zeros(pandas.concat(alldata))
  File "/opt/openquake/oq-engine/openquake/calculators/event_based.py", line 185, in strip_zeros
    assert str(df.gmv_0.dtype) == 'float32', df.gmv_0.dtype
AssertionError: float64
```

pytest summary:
```sh
======================================================= test session starts =======================================================
platform darwin -- Python 3.9.6, pytest-7.2.2, pluggy-1.0.0
rootdir: /Users/anirudh/GEM/Code/OpenQuake/oq-engine, configfile: pytest.ini
plugins: anyio-3.6.1
collected 27 items                                                                                                                

scenario_test.py .............F....FF.......                                                                                [100%]

============================================================ FAILURES =============================================================
===================================================== short test summary info =====================================================
FAILED scenario_test.py::ScenarioTestCase::test_case_21 - AssertionError: 
FAILED scenario_test.py::ScenarioTestCase::test_case_24 - AssertionError: 
FAILED scenario_test.py::ScenarioTestCase::test_case_26 - AssertionError: 
=========================================== 3 failed, 24 passed, 155 warnings in 28.69s ===========================================
```

**Comment by micheles** [comment]
They are all green me for me, perhaps it is a macos issue?

**Comment by raoanirudh** [comment]
Fail on macOS Big Sur with Python 3.9, pass on macOS Ventura with Python 3.10

**Comment by ptormene** [comment]
I am working on github actions for MacOS here: https://github.com/gem/oq-engine/pull/8970

**Comment by micheles** [comment]
Solved on cole: there the problem was an outdated version of panda, i.e. not the one in the requirements file.

**Comment by raoanirudh** [comment]
It was the same problem with my engine installation on macOS Big Sur with python 3.9 – the pandas version was outdated, updating it to the version listed in the current requirements-py39-macos_x86_64.txt file resolves the issue for me. Happy to close this issue.
