### ISSUE TITLE
Issue with hazard disagregation calculation on v3.16.6

### ISSUE THREAD

**Issue by alejocaldeGEM** [gem/oq-engine#9116]
During our workshop in Croatia, some of the users of UniZagreb shared with us hazard disaggregation calculations that fail in version 3.16.6. I can confirm that this issue does not occur when I run the calculation using the current master branch. This could mean that the issue has been addresed, but not yet implemented in the LTS. @kejohnso took a look at the files and confirmed having seen this issue in previous version of the engine. Worth taking a closer look before the new release. 

I am attaching the calculation files for your reference. The error can be replicated by running any of the two disaggregation.ini files. 

[ESHM Zagreb files.zip](https://github.com/gem/oq-engine/files/12928990/ESHM.Zagreb.files.zip)

Thanks!

Openquake Engine v3.16.6
Windows 10

~~~Traceback (most recent call last):
  File "C:\Program Files\OpenQuake Engine\python3\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\OpenQuake Engine\python3\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\OpenQuake Engine\python3\Scripts\oq.exe\__main__.py", line 7, in <module>
  File "C:\Program Files\OpenQuake Engine\python3\lib\site-packages\openquake\commands\__main__.py", line 53, in oq
    sap.run(commands, prog='oq')
  File "C:\Program Files\OpenQuake Engine\python3\lib\site-packages\openquake\baselib\sap.py", line 212, in run
    return _run(parser(funcdict, **parserkw), argv)
  File "C:\Program Files\OpenQuake Engine\python3\lib\site-packages\openquake\baselib\sap.py", line 203, in _run
    return func(**dic)
  File "C:\Program Files\OpenQuake Engine\python3\lib\site-packages\openquake\commands\engine.py", line 175, in main
    run_jobs(jobs)
  File "C:\Program Files\OpenQuake Engine\python3\lib\site-packages\openquake\engine\engine.py", line 404, in run_jobs
    run_calc(jobctx)
  File "C:\Program Files\OpenQuake Engine\python3\lib\site-packages\openquake\engine\engine.py", line 279, in run_calc
    calc.run(shutdown=True)
  File "C:\Program Files\OpenQuake Engine\python3\lib\site-packages\openquake\calculators\base.py", line 243, in run
    self.post_execute(self.result)
  File "C:\Program Files\OpenQuake Engine\python3\lib\site-packages\openquake\calculators\disaggregation.py", line 418, in post_execute
    results = {smk: _matrix(dic, T, Ma) for smk, dic in results.items()}
  File "C:\Program Files\OpenQuake Engine\python3\lib\site-packages\openquake\calculators\disaggregation.py", line 418, in <dictcomp>
    results = {smk: _matrix(dic, T, Ma) for smk, dic in results.items()}
  File "C:\Program Files\OpenQuake Engine\python3\lib\site-packages\openquake\calculators\disaggregation.py", line 64, in _matrix
    mat[trti, magi] = matrices[trti, magi]
IndexError: index 1 is out of bounds for axis 0 with size 1~

**Comment by micheles** [comment]
Unfortunately that looks really hard to fix since the disaggregation has changed completely since v3.16. Not sure about what to do (i.e. waste days to fix something which is already fixed or just tell people to upgrade and get a disaggregation that works and is 3 times faster?)

**Comment by alejocaldeGEM** [comment]
Thank you, @micheles. I guess the answer depends on how long will 3.16 be our long-term stable version. But if we have a disaggregation working properly on v3.18, the users will have one solution available. I think that's what is important.

**Comment by micheles** [comment]
I have added a clear error message telling the user to upgrade
