### ISSUE TITLE
Flexible exposure models: Allow multiple oq fields to use the same column in an exposure csv OR improve error message

### ISSUE THREAD

**Issue by nicolepaul** [gem/oq-engine#9137]
In recent models, we are commonly using the flexible exposure model functionality (https://github.com/gem/oq-engine/issues/6587)

However, in the exposure XML, one cannot specify that multiple oq fields (e.g., `residents`, `night`) map to the same column name in an exposure CSV (e.g., "total_occupants"). For example:
```xml
  <exposureFields>
    <field oq="night" input="total_occupants" />
    <field oq="residents" input="total_occupants" />
  </exposureFields>
```

If this happens, the following error is thrown
```
[2023-10-23 14:35:29 #73 INFO] Reading /Users/npaul/GEM/playground/case_16/exposure_model.xml
Traceback (most recent call last):
  File "/Users/npaul/openquake/bin/oq", line 33, in <module>
    sys.exit(load_entry_point('openquake.engine', 'console_scripts', 'oq')())
  File "/Users/npaul/GEM/oq-engine/openquake/commands/__main__.py", line 48, in oq
    sap.run(commands, prog='oq')
  File "/Users/npaul/GEM/oq-engine/openquake/baselib/sap.py", line 212, in run
    return _run(parser(funcdict, **parserkw), argv)
  File "/Users/npaul/GEM/oq-engine/openquake/baselib/sap.py", line 203, in _run
    return func(**dic)
  File "/Users/npaul/GEM/oq-engine/openquake/commands/engine.py", line 176, in main
    run_jobs(jobs)
  File "/Users/npaul/GEM/oq-engine/openquake/engine/engine.py", line 408, in run_jobs
    run_calc(jobctx)
  File "/Users/npaul/GEM/oq-engine/openquake/engine/engine.py", line 280, in run_calc
    calc.run(shutdown=True)
  File "/Users/npaul/GEM/oq-engine/openquake/calculators/base.py", line 254, in run
    raise exc from None
  File "/Users/npaul/GEM/oq-engine/openquake/calculators/base.py", line 242, in run
    self.pre_execute()
  File "/Users/npaul/GEM/oq-engine/openquake/calculators/event_based_risk.py", line 314, in pre_execute
    super().pre_execute()
  File "/Users/npaul/GEM/oq-engine/openquake/calculators/base.py", line 554, in pre_execute
    self.read_inputs()
  File "/Users/npaul/GEM/oq-engine/openquake/calculators/base.py", line 486, in read_inputs
    self._read_risk_data()
  File "/Users/npaul/GEM/oq-engine/openquake/calculators/base.py", line 803, in _read_risk_data
    haz_sitecol = readinput.get_site_collection(oq, self.datastore)
  File "/Users/npaul/GEM/oq-engine/openquake/commonlib/readinput.py", line 577, in get_site_collection
    mesh = get_mesh(oqparam, h5)
  File "/Users/npaul/GEM/oq-engine/openquake/commonlib/readinput.py", line 379, in get_mesh
    Global.exposure = get_exposure(oqparam, h5)
  File "/Users/npaul/GEM/oq-engine/openquake/commonlib/readinput.py", line 959, in get_exposure
    exposure = Global.exposure = asset.Exposure.read_all(
  File "/Users/npaul/GEM/oq-engine/openquake/risklib/asset.py", line 931, in read_all
    for exposure, df in itertools.starmap(read_exp_df, allargs):
  File "/Users/npaul/GEM/oq-engine/openquake/risklib/asset.py", line 802, in read_exp_df
    for fname, df in fname_dfs:
  File "/Users/npaul/GEM/oq-engine/openquake/risklib/asset.py", line 1018, in _read_csv
    raise InvalidFile('%s: missing %s' % (fname, missing))
openquake.baselib.InvalidFile: /Users/npaul/GEM/playground/case_16/exposure.csv: missing {'night'}
```

I propose either of the two alternatives:

1. [_Preferred_] We allow modellers to map the same exposure CSV column name to multiple oq fields in the exposure XML
2. We provide a more clear error message when this situation occurs (e.g., "The <exposure_model.xml> maps the following oq fields (<list_problematic_oq_fields>) to the same column  <column_name>. Please only provide unique column names to each oq field. As a workaround, you can duplicate <column_name>, assign a new name, and map to the other oq field(s).")

I am attaching an example model that demonstrates the issue, as well as its expected output (if run successfully).
[case_16.zip](https://github.com/gem/oq-engine/files/13072072/case_16.zip)

**Comment by micheles** [comment]
This is still broken, I get the error
```python
  File "/home/michele/oq-engine/openquake/risklib/asset.py", line 59, in add_dupl_fields
    okfield = (oqfields[f] & columns).copy().pop()
KeyError: 'pop from an empty set'
```
with the attached file 
[job.zip](https://github.com/gem/oq-engine/files/13451791/job.zip)
