### ISSUE TITLE
fiona import error

### ISSUE THREAD

**Issue by rizac** [gem/oq-engine#9224]
After upgrading yesterday ( `pip install openquake.engine==3.18.0`), I get this import error breaking the code. Looks like `fiona` should be listed in `setup.py` or made optional (possibly related to #8354):

```python
>>> from openquake.hazardlib.gsim import registry
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rizac/work/gfz/projects/sources/python/egsim/.env/py3.11.2/lib/python3.11/site-packages/openquake/hazardlib/__init__.py", line 28, in <module>
    from openquake.hazardlib import (
  File "/Users/rizac/work/gfz/projects/sources/python/egsim/.env/py3.11.2/lib/python3.11/site-packages/openquake/hazardlib/nrml.py", line 86, in <module>
    from openquake.hazardlib import valid, sourceconverter, InvalidFile
  File "/Users/rizac/work/gfz/projects/sources/python/egsim/.env/py3.11.2/lib/python3.11/site-packages/openquake/hazardlib/valid.py", line 35, in <module>
    from openquake.hazardlib import imt, scalerel, gsim, pmf, site, tom
  File "/Users/rizac/work/gfz/projects/sources/python/egsim/.env/py3.11.2/lib/python3.11/site-packages/openquake/hazardlib/gsim/__init__.py", line 28, in <module>
    import_all('openquake.hazardlib.gsim')
  File "/Users/rizac/work/gfz/projects/sources/python/egsim/.env/py3.11.2/lib/python3.11/site-packages/openquake/baselib/general.py", line 506, in import_all
    importlib.import_module(modname)
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rizac/work/gfz/projects/sources/python/egsim/.env/py3.11.2/lib/python3.11/site-packages/openquake/hazardlib/gsim/zhao_2016.py", line 32, in <module>
    import fiona
ModuleNotFoundError: No module named 'fiona'
```

**Comment by micheles** [comment]
`pip install openquake.engine==3.18.0` is not the recommended way of installing. The recommended way is using the universal installer which in practice does `pip install openquake.engine==3.18.0` but prepended by $ pip install -r requirements.txt. The right requirements to use are listed here: https://github.com/gem/oq-engine

fiona is not listed on setup.py ON PURPOSE, since we don't want people installing versions of fiona, gdal and pypro other than the ones we list in our requirements
